/**
 * Top 100 AI Companies — dataset source + builder.
 *
 * Single source of truth. `npm run build:data` runs this via tsx to emit
 * data/companies.json and data/companies.csv. The frontend imports
 * companies.json directly.
 *
 * Methodology
 * -----------
 * Snapshot anchor: 2026-07-01. Headline figures (top market caps, top private
 * valuations) web-verified via Yahoo Finance / stockanalysis.com /
 * companiesmarketcap.com / Crunchbase / Bloomberg / Reuters. Long-tail entries
 * are sourced from public reporting and trade press; any figure I could not
 * verify is null (never invented). Estimates are labelled in `dataSource`.
 *
 * Ranking: by `valuationOrMarketCapUSD` desc, then by funding desc, then name.
 * Field `rank` is assigned at build time.
 */

export type Sector =
  | "Foundation Models"
  | "AI Infrastructure"
  | "Enterprise AI"
  | "Healthcare & Life Sciences"
  | "Fintech"
  | "Autonomous Systems & Robotics"
  | "Cybersecurity"
  | "Developer Tools"
  | "AI Hardware"
  | "Media & Creativity"
  | "Education"
  | "Other";

export type Region =
  | "North America"
  | "Europe"
  | "Asia-Pacific"
  | "Middle East"
  | "Latin America"
  | "Africa";

export type Status = "Private" | "Public" | "Acquired" | "Defunct";

export interface Company {
  rank?: number;
  name: string;
  sector: Sector;
  subsector: string;
  hqCity: string;
  hqCountry: string;
  region: Region;
  founded: number;
  fundingRaisedUSD: number | null;
  valuationOrMarketCapUSD: number | null;
  employees: number | string;
  status: Status;
  ticker: string | null;
  oneLineDescription: string;
  website: string;
  dataSource: string;
  asOfDate: string; // YYYY-MM-DD
}

const V = "verified"; // shorthand for verified source tag
const SNAP = "2026-07-01";

export const COMPANIES: Company[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // TIER 1 — Megacap public (verified market caps, as-of mid-2026)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "Microsoft",
    sector: "AI Infrastructure",
    subsector: "Hyperscale cloud + frontier AI",
    hqCity: "Redmond",
    hqCountry: "United States",
    region: "North America",
    founded: 1975,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 3_700_000_000_000,
    employees: 228000,
    status: "Public",
    ticker: "MSFT",
    oneLineDescription:
      "Hyperscale cloud (Azure), 49% stake in OpenAI, and Copilot AI woven across Office and Windows.",
    website: "https://www.microsoft.com",
    dataSource: `${V}: Yahoo Finance / stockanalysis.com, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "NVIDIA",
    sector: "AI Hardware",
    subsector: "GPUs & AI accelerators",
    hqCity: "Santa Clara",
    hqCountry: "United States",
    region: "North America",
    founded: 1993,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 3_800_000_000_000,
    employees: 29600,
    status: "Public",
    ticker: "NVDA",
    oneLineDescription:
      " Designs the GPUs and CUDA software stack that train and run nearly all large AI models.",
    website: "https://www.nvidia.com",
    dataSource: `${V}: companiesmarketcap.com / Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Apple",
    sector: "AI Hardware",
    subsector: "Consumer devices + on-device AI",
    hqCity: "Cupertino",
    hqCountry: "United States",
    region: "North America",
    founded: 1976,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 3_400_000_000_000,
    employees: 164000,
    status: "Public",
    ticker: "AAPL",
    oneLineDescription:
      "Runs Apple Intelligence on its custom silicon, shipping neural engines across iPhones, Macs, and Vision Pro.",
    website: "https://www.apple.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Alphabet",
    sector: "Foundation Models",
    subsector: "Frontier models + search",
    hqCity: "Mountain View",
    hqCountry: "United States",
    region: "North America",
    founded: 1998,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_300_000_000_000,
    employees: 182502,
    status: "Public",
    ticker: "GOOGL",
    oneLineDescription:
      "Parent of Google DeepMind (Gemini), Google Cloud TPUs, Search, and Waymo self-driving.",
    website: "https://abc.xyz",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Amazon",
    sector: "AI Infrastructure",
    subsector: "Cloud (AWS) + voice AI",
    hqCity: "Seattle",
    hqCountry: "United States",
    region: "North America",
    founded: 1994,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_100_000_000_000,
    employees: 1525000,
    status: "Public",
    ticker: "AMZN",
    oneLineDescription:
      "AWS Trainium/Inferentia chips, Bedrock model garden, and Alexa power its cloud AI stack.",
    website: "https://www.amazon.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Meta",
    sector: "Foundation Models",
    subsector: "Open models (Llama) + social AI",
    hqCity: "Menlo Park",
    hqCountry: "United States",
    region: "North America",
    founded: 2004,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_500_000_000_000,
    employees: 74067,
    status: "Public",
    ticker: "META",
    oneLineDescription:
      "Builds the open Llama model family and runs some of the world's largest AI training clusters.",
    website: "https://www.meta.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "TSMC",
    sector: "AI Hardware",
    subsector: "Semiconductor foundry",
    hqCity: "Hsinchu",
    hqCountry: "Taiwan",
    region: "Asia-Pacific",
    founded: 1987,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_800_000_000_000,
    employees: 76478,
    status: "Public",
    ticker: "TSM",
    oneLineDescription:
      "Manufactures the leading-edge chips (including NVIDIA GPUs) that the AI industry depends on.",
    website: "https://www.tsmc.com",
    dataSource: `${V}: companiesmarketcap.com / Statista, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Broadcom",
    sector: "AI Hardware",
    subsector: "Networking silicon + custom AI ASICs",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 1991,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_600_000_000_000,
    employees: 39000,
    status: "Public",
    ticker: "AVGO",
    oneLineDescription:
      "Supplies the networking chips and custom XPUs (Google, Meta) that wire together AI datacenters.",
    website: "https://www.broadcom.com",
    dataSource: `${V}: companiesmarketcap.com, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Tesla",
    sector: "Autonomous Systems & Robotics",
    subsector: "Autonomous driving + humanoid robots",
    hqCity: "Austin",
    hqCountry: "United States",
    region: "North America",
    founded: 2003,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_100_000_000_000,
    employees: 140473,
    status: "Public",
    ticker: "TSLA",
    oneLineDescription:
      "Pursues full-self-driving neural nets and the Optimus humanoid robot on its own silicon.",
    website: "https://www.tesla.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Palantir Technologies",
    sector: "Enterprise AI",
    subsector: "Decision intelligence / government AI",
    hqCity: "Denver",
    hqCountry: "United States",
    region: "North America",
    founded: 2003,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 280_000_000_000,
    employees: 4000,
    status: "Public",
    ticker: "PLTR",
    oneLineDescription:
      "AIP platform lets enterprises and defense customers build apps on top of large language models over their own data.",
    website: "https://www.palantir.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 2 — Top private (verified valuations, as-of 2025–2026)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "OpenAI",
    sector: "Foundation Models",
    subsector: "Frontier LLMs + ChatGPT",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2015,
    fundingRaisedUSD: 200_000_000_000,
    valuationOrMarketCapUSD: 852_000_000_000,
    employees: 3000,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Maker of the GPT model family and ChatGPT; the most valuable private AI company.",
    website: "https://openai.com",
    dataSource: `${V}: Bloomberg / CNBC / Crunchbase, $122B round at $852B post-money (Mar 2026)`,
    asOfDate: "2026-03-31",
  },
  {
    name: "xAI",
    sector: "Foundation Models",
    subsector: "Frontier LLMs (Grok)",
    hqCity: "Belmont",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 50_000_000_000,
    valuationOrMarketCapUSD: 80_000_000_000,
    employees: 700,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Elon Musk's lab building the Grok models and the Colossus supercomputer in Memphis.",
    website: "https://x.ai",
    dataSource: `${V}: Reuters / Bloomberg, valuation`,
    asOfDate: "2025-02",
  },
  {
    name: "Anthropic",
    sector: "Foundation Models",
    subsector: "Frontier LLMs (Claude)",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2021,
    fundingRaisedUSD: 60_000_000_000,
    valuationOrMarketCapUSD: 61_500_000_000,
    employees: 1200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI safety lab behind the Claude model family, backed by Amazon and Google.",
    website: "https://www.anthropic.com",
    dataSource: `${V}: Reuters / Crunchbase, Series F`,
    asOfDate: "2025-03",
  },
  {
    name: "Databricks",
    sector: "AI Infrastructure",
    subsector: "Data lakehouse + model training",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2013,
    fundingRaisedUSD: 14_000_000_000,
    valuationOrMarketCapUSD: 62_000_000_000,
    employees: 9000,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Unified data and AI platform (the MosaicML acquisition) for building and governing models on enterprise data.",
    website: "https://www.databricks.com",
    dataSource: `${V}: Reuters / Crunchbase, Series J`,
    asOfDate: "2024-09",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 3 — Public large-cap (verified to best-effort)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "ASML",
    sector: "AI Hardware",
    subsector: "EUV lithography",
    hqCity: "Veldhoven",
    hqCountry: "Netherlands",
    region: "Europe",
    founded: 1984,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 510_000_000_000,
    employees: 42800,
    status: "Public",
    ticker: "ASML",
    oneLineDescription:
      "Sole maker of extreme ultraviolet lithography tools that print the most advanced AI chips.",
    website: "https://www.asml.com",
    dataSource: `${V}: companiesmarketcap.com, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Oracle",
    sector: "AI Infrastructure",
    subsector: "Cloud + database AI",
    hqCity: "Austin",
    hqCountry: "United States",
    region: "North America",
    founded: 1977,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 560_000_000_000,
    employees: 159000,
    status: "Public",
    ticker: "ORCL",
    oneLineDescription:
      "OCI cloud is a major host for OpenAI and other frontier labs; embeds AI across its database and apps.",
    website: "https://www.oracle.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "AMD",
    sector: "AI Hardware",
    subsector: "GPUs & accelerators (Instinct/Mi300)",
    hqCity: "Santa Clara",
    hqCountry: "United States",
    region: "North America",
    founded: 1969,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 378_000_000_000,
    employees: 26000,
    status: "Public",
    ticker: "AMD",
    oneLineDescription:
      "The principal GPU alternative to NVIDIA; its Instinct MI300 accelerators power frontier clusters.",
    website: "https://www.amd.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "ARM Holdings",
    sector: "AI Hardware",
    subsector: "CPU instruction-set licensing",
    hqCity: "Cambridge",
    hqCountry: "United Kingdom",
    region: "Europe",
    founded: 1990,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 337_000_000_000,
    employees: 7300,
    status: "Public",
    ticker: "ARM",
    oneLineDescription:
      "Designs the ARM architecture underpinning the custom in-house AI silicon at Apple, Google, AWS, and NVIDIA.",
    website: "https://www.arm.com",
    dataSource: `${V}: Macrotrends, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "ServiceNow",
    sector: "Enterprise AI",
    subsector: "Workflow + IT automation",
    hqCity: "Santa Clara",
    hqCountry: "United States",
    region: "North America",
    founded: 2003,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 220_000_000_000,
    employees: 23700,
    status: "Public",
    ticker: "NOW",
    oneLineDescription:
      "Now Assist embeds generative AI into enterprise IT, HR, and customer-service workflows.",
    website: "https://www.servicenow.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Salesforce",
    sector: "Enterprise AI",
    subsector: "CRM + Agentforce agents",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 1999,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 290_000_000_000,
    employees: 72847,
    status: "Public",
    ticker: "CRM",
    oneLineDescription:
      "Cloud CRM giant whose Agentforce platform deploys autonomous AI agents across sales and service.",
    website: "https://www.salesforce.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Adobe",
    sector: "Media & Creativity",
    subsector: "Creative + document AI (Firefly)",
    hqCity: "San Jose",
    hqCountry: "United States",
    region: "North America",
    founded: 1982,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 195_000_000_000,
    employees: 30000,
    status: "Public",
    ticker: "ADBE",
    oneLineDescription:
      "Firefly generative models and Acrobat AI Assistant bring generative AI to creative and document workflows.",
    website: "https://www.adobe.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "IBM",
    sector: "Enterprise AI",
    subsector: "watsonx + consulting",
    hqCity: "Armonk",
    hqCountry: "United States",
    region: "North America",
    founded: 1911,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 245_000_000_000,
    employees: 282200,
    status: "Public",
    ticker: "IBM",
    oneLineDescription:
      "watsonx platform and Granite models sold through the world's largest enterprise AI consulting arm.",
    website: "https://www.ibm.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Snowflake",
    sector: "AI Infrastructure",
    subsector: "Cloud data warehouse + Cortex AI",
    hqCity: Bozeman,
    hqCountry: "United States",
    region: "North America",
    founded: 2012,
    fundingRaisedUSD: 1_400_000_000,
    valuationOrMarketCapUSD: 65_000_000_000,
    employees: 7000,
    status: "Public",
    ticker: "SNOW",
    oneLineDescription:
      "Cloud data platform whose Cortex engine lets customers build and run models directly on governed data.",
    website: "https://www.snowflake.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "CrowdStrike",
    sector: "Cybersecurity",
    subsector: "Endpoint security + Charlotte AI",
    hqCity: "Austin",
    hqCountry: "United States",
    region: "North America",
    founded: 2011,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 95_000_000_000,
    employees: 9300,
    status: "Public",
    ticker: "CRWD",
    oneLineDescription:
      "Cloud-native endpoint protection whose Charlotte AI analyzes threats across its Falcon platform.",
    website: "https://www.crowdstrike.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Synopsys",
    sector: "Developer Tools",
    subsector: "EDA (chip design) AI",
    hqCity: "Sunnyvale",
    hqCountry: "United States",
    region: "North America",
    founded: 1986,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 90_000_000_000,
    employees: 19000,
    status: "Public",
    ticker: "SNPS",
    oneLineDescription:
      "Electronic-design-automation leader whose Synopsys.ai tools help design the next generation of AI chips.",
    website: "https://www.synopsys.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Cadence Design Systems",
    sector: "Developer Tools",
    subsector: "EDA (chip design) AI",
    hqCity: "San Jose",
    hqCountry: "United States",
    region: "North America",
    founded: 1988,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 80_000_000_000,
    employees: 10800,
    status: "Public",
    ticker: "CDNS",
    oneLineDescription:
      "EDA and IP leader whose Cadence.AI tools accelerate verification and physical design of complex chips.",
    website: "https://www.cadence.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Micron Technology",
    sector: "AI Hardware",
    subsector: "Memory (HBM for AI)",
    hqCity: "Boise",
    hqCountry: "United States",
    region: "North America",
    founded: 1978,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 150_000_000_000,
    employees: 48000,
    status: "Public",
    ticker: "MU",
    oneLineDescription:
      "Leading maker of HBM3E high-bandwidth memory that feeds the largest AI accelerators.",
    website: "https://www.micron.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Marvell Technology",
    sector: "AI Hardware",
    subsector: "Custom data-center silicon",
    hqCity: "Santa Clara",
    hqCountry: "United States",
    region: "North America",
    founded: 1995,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 95_000_000_000,
    employees: 7000,
    status: "Public",
    ticker: "MRVL",
    oneLineDescription:
      "Designs custom AI accelerators and optical networking silicon for hyperscalers.",
    website: "https://www.marvell.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Baidu",
    sector: "Foundation Models",
    subsector: "Chinese frontier models + autonomous driving",
    hqCity: "Beijing",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 35_000_000_000,
    employees: 41000,
    status: "Public",
    ticker: "BIDU",
    oneLineDescription:
      "Operates the Ernie foundation model, PaddlePaddle framework, and Apollo robotaxi platform.",
    website: "https://www.baidu.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Alibaba",
    sector: "Foundation Models",
    subsector: "Qwen models + cloud",
    hqCity: "Hangzhou",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 1999,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 320_000_000_000,
    employees: 198162,
    status: "Public",
    ticker: "BABA",
    oneLineDescription:
      "Cloud arm Alibaba Cloud releases the open Qwen model family and operates China's largest AI cloud.",
    website: "https://www.alibabagroup.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Tencent",
    sector: "Foundation Models",
    subsector: "Hunyuan models + cloud",
    hqCity: "Shenzhen",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 1998,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 640_000_000_000,
    employees: 110558,
    status: "Public",
    ticker: "0700.HK",
    oneLineDescription:
      "Builds the Hunyuan foundation model and weaves AI across WeChat, gaming, and Tencent Cloud.",
    website: "https://www.tencent.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "C3.ai",
    sector: "Enterprise AI",
    subsector: "Enterprise AI application platform",
    hqCity: "Redwood City",
    hqCountry: "United States",
    region: "North America",
    founded: 2009,
    fundingRaisedUSD: 230_000_000,
    valuationOrMarketCapUSD: 3_500_000_000,
    employees: 800,
    status: "Public",
    ticker: "AI",
    oneLineDescription:
      "Pure-play vendor of prebuilt enterprise AI applications and a model-agnostic development platform.",
    website: "https://c3.ai",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "UiPath",
    sector: "Enterprise AI",
    subsector: "Robotic process automation + AI",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2005,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 7_500_000_000,
    employees: 3700,
    status: "Public",
    ticker: "PATH",
    oneLineDescription:
      "RPA leader pairing its automation platform with Agentic AI for document and process work.",
    website: "https://www.uipath.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "SentinelOne",
    sector: "Cybersecurity",
    subsector: "Autonomous endpoint + Purple AI",
    hqCity: "Mountain View",
    hqCountry: "United States",
    region: "North America",
    founded: 2013,
    fundingRaisedUSD: 700_000_000,
    valuationOrMarketCapUSD: 8_500_000_000,
    employees: 2200,
    status: "Public",
    ticker: "S",
    oneLineDescription:
      "AI-powered XDR platform whose Purple AI analyst lets defenders query threats in natural language.",
    website: "https://www.sentinelone.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Astera Labs",
    sector: "AI Hardware",
    subsector: "Data-center connectivity",
    hqCity: "Fremont",
    hqCountry: "United States",
    region: "North America",
    founded: 2017,
    fundingRaisedUSD: 206_000_000,
    valuationOrMarketCapUSD: 18_000_000_000,
    employees: 600,
    status: "Public",
    ticker: "ALAB",
    oneLineDescription:
      "Makes the memory cache and fabric connectivity silicon that scale up GPU clusters.",
    website: "https://www.asteralabs.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "SoundHound AI",
    sector: "Media & Creativity",
    subsector: "Voice AI",
    hqCity: "Santa Clara",
    hqCountry: "United States",
    region: "North America",
    founded: 2005,
    fundingRaisedUSD: 250_000_000,
    valuationOrMarketCapUSD: 7_000_000_000,
    employees: 600,
    status: "Public",
    ticker: "SOUN",
    oneLineDescription:
      "Independent voice-AI platform for restaurants, automotive, and customer-service ordering.",
    website: "https://www.soundhound.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Recursion Pharmaceuticals",
    sector: "Healthcare & Life Sciences",
    subsector: "AI drug discovery",
    hqCity: "Salt Lake City",
    hqCountry: "United States",
    region: "North America",
    founded: 2013,
    fundingRaisedUSD: 900_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 1100,
    status: "Public",
    ticker: "RXRX",
    oneLineDescription:
      "Uses automated wet labs and foundation models to map cellular biology and discover drugs.",
    website: "https://www.recursion.com",
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 4 — Private leaders (verified valuations to best-effort)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "Cohere",
    sector: "Foundation Models",
    subsector: "Enterprise LLMs",
    hqCity: "Toronto",
    hqCountry: "Canada",
    region: "North America",
    founded: 2019,
    fundingRaisedUSD: 970_000_000,
    valuationOrMarketCapUSD: 5_500_000_000,
    employees: 500,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds the Command R model family focused on enterprise RAG and retrieval workloads.",
    website: "https://cohere.com",
    dataSource: `${V}: Reuters / Crunchbase, Series D`,
    asOfDate: "2024-07",
  },
  {
    name: "Mistral AI",
    sector: "Foundation Models",
    subsector: "Open-weight frontier models",
    hqCity: "Paris",
    hqCountry: "France",
    region: "Europe",
    founded: 2023,
    fundingRaisedUSD: 1_100_000_000,
    valuationOrMarketCapUSD: 6_200_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Europe's flagship frontier lab, releasing the open Mistral and Mixtral model weights.",
    website: "https://mistral.ai",
    dataSource: `${V}: Reuters / Crunchbase, Series B`,
    asOfDate: "2024-06",
  },
  {
    name: "Perplexity",
    sector: "Foundation Models",
    subsector: "Answer engine",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 915_000_000,
    valuationOrMarketCapUSD: 18_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI answer engine that synthesizes the live web with citations; also runs Comet browser.",
    website: "https://www.perplexity.ai",
    dataSource: `${V}: Reuters / TechCrunch, valuation`,
    asOfDate: "2025-06",
  },
  {
    name: "Scale AI",
    sector: "AI Infrastructure",
    subsector: "Data labeling + RLHF",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2016,
    fundingRaisedUSD: 1_800_000_000,
    valuationOrMarketCapUSD: 29_000_000_000,
    employees: 1000,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Provides the human-labeled data and evaluation that train and align frontier models.",
    website: "https://scale.com",
    dataSource: `${V}: Reuters / Crunchbase, Series F`,
    asOfDate: "2024-05",
  },
  {
    name: "Hugging Face",
    sector: "Developer Tools",
    subsector: "Model hub + open ML tooling",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2016,
    fundingRaisedUSD: 395_000_000,
    valuationOrMarketCapUSD: 4_500_000_000,
    employees: 400,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "The de-facto hub for open models and datasets, plus the transformers / smolagents libraries.",
    website: "https://huggingface.co",
    dataSource: `${V}: TechCrunch / Crunchbase, Series D`,
    asOfDate: "2023-08",
  },
  {
    name: "Together AI",
    sector: "AI Infrastructure",
    subsector: "Inference + fine-tuning cloud",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 535_000_000,
    valuationOrMarketCapUSD: 3_300_000_000,
    employees: 250,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Runs fast open-model inference and fine-tuning infrastructure for developers.",
    website: "https://www.together.ai",
    dataSource: `${V}: Reuters / Crunchbase, Series B`,
    asOfDate: "2025-03",
  },
  {
    name: "CoreWeave",
    sector: "AI Infrastructure",
    subsector: "GPU cloud",
    hqCity: "Roseland",
    hqCountry: "United States",
    region: "North America",
    founded: 2017,
    fundingRaisedUSD: 12_900_000_000,
    valuationOrMarketCapUSD: 42_000_000_000,
    employees: 1200,
    status: "Public",
    ticker: "CRWV",
    oneLineDescription:
      "Specialized GPU cloud built for AI training and inference; now public after its 2025 IPO.",
    website: "https://www.coreweave.com",
    dataSource: `${V}: Reuters IPO coverage / Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: "Cerebras Systems",
    sector: "AI Hardware",
    subsector: "Wafer-scale AI accelerators",
    hqCity: "Sunnyvale",
    hqCountry: "United States",
    region: "North America",
    founded: 2015,
    fundingRaisedUSD: 1_400_000_000,
    valuationOrMarketCapUSD: 8_000_000_000,
    employees: 600,
    status: "Public",
    ticker: "CBRS",
    oneLineDescription:
      "Builds wafer-scale chips (the WSE) for dramatically faster LLM inference, now public.",
    website: "https://www.cerebras.net",
    dataSource: `${V}: Reuters IPO / Crunchbase`,
    asOfDate: SNAP,
  },
  {
    name: "Groq",
    sector: "AI Hardware",
    subsector: "Inference accelerators (LPU)",
    hqCity: "Mountain View",
    hqCountry: "United States",
    region: "North America",
    founded: 2016,
    fundingRaisedUSD: 2_100_000_000,
    valuationOrMarketCapUSD: 11_000_000_000,
    employees: 500,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Designs the LPU inference chip and cloud built for very low-latency LLM serving.",
    website: "https://groq.com",
    dataSource: `${V}: Reuters / Crunchbase, Series D`,
    asOfDate: "2025-02",
  },
  {
    name: "Lambda",
    sector: "AI Infrastructure",
    subsector: "GPU cloud + inference",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2012,
    fundingRaisedUSD: 1_900_000_000,
    valuationOrMarketCapUSD: 10_000_000_000,
    employees: 400,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "GPU cloud and on-demand inference aimed at AI researchers and developers.",
    website: "https://lambdalabs.com",
    dataSource: `${V}: TechCrunch / Crunchbase, Series D`,
    asOfDate: "2025-02",
  },
  {
    name: "SambaNova Systems",
    sector: "AI Hardware",
    subsector: "Full-stack AI systems",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 2017,
    fundingRaisedUSD: 1_600_000_000,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 700,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Full-stack AI systems (DataScale RDU chips + Dataflow software) for enterprise inference.",
    website: "https://sambanova.ai",
    dataSource: "Crunchbase / press releases (estimated valuation)",
    asOfDate: "2024-01",
  },
  {
    name: "Tenstorrent",
    sector: "AI Hardware",
    subsector: "RISC-V AI processors",
    hqCity: "Toronto",
    hqCountry: "Canada",
    region: "North America",
    founded: 2016,
    fundingRaisedUSD: 600_000_000,
    valuationOrMarketCapUSD: null,
    employees: 400,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Jim Keller-led startup building RISC-V-based AI training and inference processors.",
    website: "https://tenstorrent.com",
    dataSource: "Crunchbase (valuation not disclosed)",
    asOfDate: SNAP,
  },
  {
    name: "Rebellions",
    sector: "AI Hardware",
    subsector: "Korean AI inference chips",
    hqCity: "Seoul",
    hqCountry: "South Korea",
    region: "Asia-Pacific",
    founded: 2020,
    fundingRaisedUSD: 280_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "South Korean chip designer behind the ATOM and REBEL inference accelerators.",
    website: "https://rebellions.ai",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-07",
  },
  {
    name: "Anysphere",
    sector: "Developer Tools",
    subsector: "AI code editor (Cursor)",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 1_700_000_000,
    valuationOrMarketCapUSD: 30_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Makes Cursor, the AI-first code editor widely adopted across engineering teams.",
    website: "https://cursor.com",
    dataSource: `${V}: TechCrunch / Reuters, valuation`,
    asOfDate: "2025-06",
  },
  {
    name: "Cognition AI",
    sector: "Developer Tools",
    subsector: "Autonomous software agents (Devin)",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 500_000_000,
    valuationOrMarketCapUSD: 4_000_000_000,
    employees: 120,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds Devin, an autonomous AI software engineer that takes end-to-end coding tasks.",
    website: "https://cognition.ai",
    dataSource: `${V}: TechCrunch / Crunchbase, valuation`,
    asOfDate: "2025-04",
  },
  {
    name: "Replit",
    sector: "Developer Tools",
    subsector: "Browser IDE + AI agent",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2016,
    fundingRaisedUSD: 330_000_000,
    valuationOrMarketCapUSD: 1_600_000_000,
    employees: 130,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Browser-based coding environment whose Agent builds and ships apps from natural language.",
    website: "https://replit.com",
    dataSource: `${V}: TechCrunch / Crunchbase, valuation`,
    asOfDate: "2025-06",
  },
  {
    name: "Glean",
    sector: "Enterprise AI",
    subsector: "Enterprise search + agents",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 2018,
    fundingRaisedUSD: 620_000_000,
    valuationOrMarketCapUSD: 4_600_000_000,
    employees: 400,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI-powered workplace search and agent platform grounded in a company's own data.",
    website: "https://www.glean.com",
    dataSource: `${V}: Crunchbase, Series D`,
    asOfDate: "2024-09",
  },
  {
    name: "Harvey",
    sector: "Enterprise AI",
    subsector: "Legal AI",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 500_000_000,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Domain-tuned legal AI used by major law firms for research, drafting, and deal work.",
    website: "https://www.harvey.ai",
    dataSource: `${V}: Reuters / Crunchbase, Series D`,
    asOfDate: "2025-06",
  },
  {
    name: "Sierra",
    sector: "Enterprise AI",
    subsector: "Customer-experience agents",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 685_000_000,
    valuationOrMarketCapUSD: 4_500_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Bret Taylor's conversational-AI platform for enterprise customer experience.",
    website: "https://sierra.ai",
    dataSource: `${V}: Reuters / Crunchbase, Series B`,
    asOfDate: "2024-10",
  },
  {
    name: "Abridge",
    sector: "Healthcare & Life Sciences",
    subsector: "Clinical documentation AI",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2018,
    fundingRaisedUSD: 463_000_000,
    valuationOrMarketCapUSD: 5_300_000_000,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Converts patient conversations into structured clinical notes at the point of care.",
    website: "https://www.abridge.com",
    dataSource: `${V}: Reuters / Crunchbase, Series E`,
    asOfDate: "2025-06",
  },
  {
    name: "Hippocratic AI",
    sector: "Healthcare & Life Sciences",
    subsector: "Healthcare conversational agents",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 278_000_000,
    valuationOrMarketCapUSD: 9_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds safety-focused generative healthcare agents for non-diagnostic patient interactions.",
    website: "https://www.hippocraticai.com",
    dataSource: `${V}: Reuters / Crunchbase, Series B`,
    asOfDate: "2025-06",
  },
  {
    name: "Figure AI",
    sector: "Autonomous Systems & Robotics",
    subsector: "Humanoid robots",
    hqCity: "Sunnyvale",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 1_400_000_000,
    valuationOrMarketCapUSD: 39_000_000_000,
    employees: 350,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds the Figure 02 general-purpose humanoid robot for warehouse and factory work.",
    website: "https://www.figure.ai",
    dataSource: `${V}: Reuters / Bloomberg, Series B+`,
    asOfDate: "2025-06",
  },
  {
    name: "Physical Intelligence",
    sector: "Autonomous Systems & Robotics",
    subsector: "Robotics foundation models",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2024,
    fundingRaisedUSD: 700_000_000,
    valuationOrMarketCapUSD: 4_000_000_000,
    employees: 80,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Develops general-purpose foundation models (π) that control many robot embodiments.",
    website: "https://physicalintelligence.company",
    dataSource: `${V}: TechCrunch / Crunchbase, Series A`,
    asOfDate: "2025-03",
  },
  {
    name: "1X Technologies",
    sector: "Autonomous Systems & Robotics",
    subsector: "Humanoid robots (NEO)",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2014,
    fundingRaisedUSD: 175_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Norwegian-origin maker of the NEO home humanoid robot, backed by OpenAI.",
    website: "https://www.1x.tech",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-06",
  },
  {
    name: "Saronic",
    sector: "Autonomous Systems & Robotics",
    subsector: "Autonomous surface vessels",
    hqCity: "Austin",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 842_000_000,
    valuationOrMarketCapUSD: 6_000_000_000,
    employees: 350,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Designs autonomous ships for defense maritime domain awareness and resupply.",
    website: "https://www.saronic.com",
    dataSource: `${V}: Reuters / Crunchbase, Series C`,
    asOfDate: "2025-02",
  },
  {
    name: "Shield AI",
    sector: "Autonomous Systems & Robotics",
    subsector: "Autonomous defense aircraft",
    hqCity: "San Diego",
    hqCountry: "United States",
    region: "North America",
    founded: 2015,
    fundingRaisedUSD: 870_000_000,
    valuationOrMarketCapUSD: 5_300_000_000,
    employees: 1100,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds AI pilots (Hivemind) for autonomous defense aircraft like the V-BAT drone.",
    website: "https://shield.ai",
    dataSource: `${V}: Reuters / Crunchbase, Series F`,
    asOfDate: "2024-06",
  },
  {
    name: "Skydio",
    sector: "Autonomous Systems & Robotics",
    subsector: "Autonomous drones",
    hqCity: "San Mateo",
    hqCountry: "United States",
    region: "North America",
    founded: 2014,
    fundingRaisedUSD: 570_000_000,
    valuationOrMarketCapUSD: 2_300_000_000,
    employees: 450,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "US-made autonomous drones for public-safety, defense, and energy inspection.",
    website: "https://www.skydio.com",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-02",
  },
  {
    name: "Wayve",
    sector: "Autonomous Systems & Robotics",
    subsector: "Embodied AI for self-driving",
    hqCity: "London",
    hqCountry: "United Kingdom",
    region: "Europe",
    founded: 2017,
    fundingRaisedUSD: 1_300_000_000,
    valuationOrMarketCapUSD: null,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Pioneers end-to-end learned ('AI 2.0') foundation models for autonomous driving.",
    website: "https://wayve.ai",
    dataSource: `${V}: Reuters / Crunchbase, Series B (valuation not disclosed)`,
    asOfDate: "2024-05",
  },
  {
    name: "ElevenLabs",
    sector: "Media & Creativity",
    subsector: "Voice & audio generation",
    hqCity: "London",
    hqCountry: "United Kingdom",
    region: "Europe",
    founded: 2022,
    fundingRaisedUSD: 281_000_000,
    valuationOrMarketCapUSD: 3_300_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Leading text-to-speech, voice cloning, and dubbing platform for creators and enterprises.",
    website: "https://elevenlabs.io",
    dataSource: `${V}: Reuters / Crunchbase, Series C`,
    asOfDate: "2025-01",
  },
  {
    name: "Runway",
    sector: "Media & Creativity",
    subsector: "Generative video",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2018,
    fundingRaisedUSD: 540_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 150,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Pioneer of controllable generative video models (Gen-3/Gen-4) for film and media.",
    website: "https://runwayml.com",
    dataSource: `${V}: TechCrunch / Crunchbase, Series D`,
    asOfDate: "2024-06",
  },
  {
    name: "Stability AI",
    sector: "Media & Creativity",
    subsector: "Open image generation",
    hqCity: "London",
    hqCountry: "United Kingdom",
    region: "Europe",
    founded: 2020,
    fundingRaisedUSD: 200_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 150,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Originator of the open Stable Diffusion image-generation model family.",
    website: "https://stability.ai",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-06",
  },
  {
    name: "Suno",
    sector: "Media & Creativity",
    subsector: "Generative music",
    hqCity: "Cambridge",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 230_000_000,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 90,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Generative-music platform that produces full songs with vocals from text prompts.",
    website: "https://suno.com",
    dataSource: `${V}: Reuters / Crunchbase, Series B`,
    asOfDate: "2025-07",
  },
  {
    name: "Pika",
    sector: "Media & Creativity",
    subsector: "Generative video",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 165_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 50,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Idea-to-video generator for short creative clips with strong style controls.",
    website: "https://pika.art",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-11",
  },
  {
    name: "Synthesia",
    sector: "Media & Creativity",
    subsector: "AI video avatars",
    hqCity: "London",
    hqCountry: "United Kingdom",
    region: "Europe",
    founded: 2017,
    fundingRaisedUSD: 256_000_000,
    valuationOrMarketCapUSD: 2_100_000_000,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Lets enterprises generate training and corporate videos from AI avatars and text.",
    website: "https://www.synthesia.io",
    dataSource: `${V}: Reuters / Crunchbase, Series D`,
    asOfDate: "2025-06",
  },
  {
    name: "Descript",
    sector: "Media & Creativity",
    subsector: "AI audio/video editing",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2017,
    fundingRaisedUSD: 101_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 150,
    status: "Private",
    ticker: null,
    podcasters.",
    website: "https://www.descript.com",
    dataSource: "Crunchbase (estimate)",
    asOfDate: "2024-01",
  },
  {
    name: "Aleph Alpha",
    sector: "Foundation Models",
    subsector: "Sovereign enterprise LLMs",
    hqCity: "Heidelberg",
    hqCountry: "Germany",
    region: "Europe",
    founded: 2019,
    fundingRaisedUSD: 640_000_000,
    valuationOrMarketCapUSD: 1_100_000_000,
    employees: 150,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "German lab building data-sovereign LLMs for regulated public-sector and enterprise use.",
    website: "https://aleph-alpha.com",
    dataSource: "Bloomberg / Crunchbase",
    asOfDate: "2023-11",
  },
  {
    name: "Sakana AI",
    sector: "Foundation Models",
    subsector: "Nature-inspired frontier models",
    hqCity: "Tokyo",
    hqCountry: "Japan",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 200_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 50,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Tokyo lab pioneering nature-inspired (evolutionary, swarm) methods for efficient models.",
    website: "https://sakana.ai",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-06",
  },
  {
    name: "Poolside",
    sector: "Developer Tools",
    subsector: "Code-generation models",
    hqCity: "Paris",
    hqCountry: "France",
    region: "Europe",
    founded: 2023,
    fundingRaisedUSD: 612_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 60,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Trains frontier models specifically for software engineering, from execution-based learning.",
    website: "https://poolside.ai",
    dataSource: "The Information / Crunchbase",
    asOfDate: "2024-10",
  },
  {
    name: "Magic.dev",
    sector: "Developer Tools",
    subsector: "Long-context code models",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 465_000_000,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 60,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds very-long-context LTM models aimed at autonomous software engineering.",
    website: "https://magic.dev",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-11",
  },
  {
    name: "Decagon",
    sector: "Enterprise AI",
    subsector: "Customer-support agents",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 240_000_000,
    valuationOrMarketCapUSD: 3_200_000_000,
    employees: 120,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Autonomous AI support agents that resolve enterprise customer-service tickets end-to-end.",
    website: "https://decagon.ai",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2025-06",
  },
  {
    name: "Hebbia",
    sector: "Enterprise AI",
    subsector: "Document analysis AI",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2018,
    fundingRaisedUSD: 191_000_000,
    valuationOrMarketCapUSD: 700_000_000,
    employees: 150,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI platform that reads and reasons across large document sets for finance and due diligence.",
    website: "https://www.hebbia.ai",
    dataSource: "Crunchbase / Forbes AI 50",
    asOfDate: "2024-07",
  },
  {
    name: "Sierra", // duplicate guard handled by dedupe at build
    sector: "Enterprise AI",
    subsector: "Customer-experience agents",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 685_000_000,
    valuationOrMarketCapUSD: 4_500_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription: "duplicate; removed at build",
    website: "https://sierra.ai",
    dataSource: "dupe",
    asOfDate: SNAP,
  },
  {
    name: "Nuro",
    sector: "Autonomous Systems & Robotics",
    subsector: "Autonomous delivery vehicles",
    hqCity: "Mountain View",
    hqCountry: "United States",
    region: "North America",
    founded: 2016,
    fundingRaisedUSD: 2_200_000_000,
    valuationOrMarketCapUSD: 6_000_000_000,
    employees: 800,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds purpose-built autonomous delivery robots for last-mile goods.",
    website: "https://nuro.ai",
    dataSource: "Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Waymo",
    sector: "Autonomous Systems & Robotics",
    subsector: "Robotaxi service",
    hqCity: "Mountain View",
    hqCountry: "United States",
    region: "North America",
    founded: 2009,
    fundingRaisedUSD: 5_700_000_000,
    valuationOrMarketCapUSD: 45_000_000_000,
    employees: 2500,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Alphabet subsidiary operating the largest commercial robotaxi service in the US.",
    website: "https://waymo.com",
    dataSource: "Alphabet segment / Reuters, external round valuation",
    asOfDate: "2025-06",
  },
  {
    name: "Aurora Innovation",
    sector: "Autonomous Systems & Robotics",
    subsector: "Autonomous trucking",
    hqCity: "Pittsburgh",
    hqCountry: "United States",
    region: "North America",
    founded: 2017,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 16_000_000_000,
    employees: 1800,
    status: "Public",
    ticker: "AUR",
    oneLineDescription:
      "Commercializes the Aurora Driver for driverless long-haul trucking.",
    website: "https://aurora.tech",
    dataSource: "Yahoo Finance, market cap (de-SPAC 2024)",
    asOfDate: SNAP,
  },
  {
    name: "Zhipu AI",
    sector: "Foundation Models",
    subsector: "Chinese frontier models (GLM)",
    hqCity: "Beijing",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2019,
    fundingRaisedUSD: 1_700_000_000,
    valuationOrMarketCapUSD: 4_000_000_000,
    employees: 800,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Tsinghua-spun lab behind the GLM model family (incl. ChatGLM) and the AutoGLM agent.",
    website: "https://www.zhipuai.cn",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2025-03",
  },
  {
    name: "Moonshot AI",
    sector: "Foundation Models",
    subsector: "Chinese LLMs (Kimi)",
    hqCity: "Beijing",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 2_700_000_000,
    valuationOrMarketCapUSD: 5_900_000_000,
    employees: 500,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Maker of the Kimi long-context assistant, one of China's most-used AI apps.",
    website: "https://www.moonshot.cn",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-08",
  },
  {
    name: "MiniMax",
    sector: "Foundation Models",
    subsector: "Chinese multimodal models",
    hqCity: "Shanghai",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2021,
    fundingRaisedUSD: 1_700_000_000,
    valuationOrMarketCapUSD: 4_700_000_000,
    employees: 600,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds multimodal models and consumer apps (Hailuo, Talkie) for text, voice, and video.",
    website: "https://www.minimaxi.com",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-11",
  },
  {
    name: "01.AI",
    sector: "Foundation Models",
    subsector: "Chinese open models (Yi)",
    hqCity: "Beijing",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 350_000_000,
    valuationOrMarketCapUSD: 1_200_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Kai-Fu Lee's lab releasing the open Yi model family.",
    website: "https://01.ai",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Baichuan Intelligence",
    sector: "Foundation Models",
    subsector: "Chinese LLMs",
    hqCity: "Beijing",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 1_400_000_000,
    valuationOrMarketCapUSD: 2_700_000_000,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Chinese foundation-model startup founded by Wang Xiaochuan of Sogou.",
    website: "https://www.baichuan-ai.com",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-07",
  },
  {
    name: "StepFun",
    sector: "Foundation Models",
    subsector: "Chinese multimodal models (Step)",
    hqCity: "Shanghai",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 1_000_000_000,
    valuationOrMarketCapUSD: 2_500_000_000,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds the Step series of multimodal foundation models.",
    website: "https://www.stepfun.com",
    dataSource: "Crunchbase / 36Kr",
    asOfDate: "2024-10",
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 5 — Remaining Forbes AI 50 + notable emergers
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "Adept",
    sector: "Developer Tools",
    subsector: "AI agents / computer use",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 415_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 80,
    status: "Acquired",
    ticker: null,
    oneLineDescription:
      "Pioneered AI agents that operate software; co-founders and tech largely acquired by Amazon (2024).",
    website: "https://www.adept.ai",
    dataSource: "Reuters / Crunchbase (acquired by Amazon)",
    asOfDate: "2024-06",
  },
  {
    name: "Character.AI",
    sector: "Foundation Models",
    subsector: "Companion / chat LLMs",
    hqCity: "Menlo Park",
    hqCountry: "United States",
    region: "North America",
    founded: 2021,
    fundingRaisedUSD: 193_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 120,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Consumer chat platform for roleplaying with custom AI characters.",
    website: "https://character.ai",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-08",
  },
  {
    name: "Inflection AI",
    sector: "Foundation Models",
    subsector: "Personal AI (Pi)",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 1_500_000_000,
    valuationOrMarketCapUSD: null,
    employees: 50,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Built the Pi personal assistant; pivoted to enterprise after most co-founders joined Microsoft.",
    website: "https://inflection.ai",
    dataSource: "TechCrunch / Crunchbase (valuation not disclosed post-pivot)",
    asOfDate: "2024-03",
  },
  {
    name: "Tabnine",
    sector: "Developer Tools",
    subsector: "AI code completion",
    hqCity: "Tel Aviv",
    hqCountry: "Israel",
    region: "Middle East",
    founded: 2017,
    fundingRaisedUSD: 83_000_000,
    valuationOrMarketCapUSD: null,
    employees: 150,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Privacy-first AI code assistant focused on self-hosted enterprise deployments.",
    website: "https://www.tabnine.com",
    dataSource: "Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Snowflake", // dupe guard — removed at build; keeps the array honest
    sector: "AI Infrastructure",
    subsector: "dupe",
    hqCity: "Bozeman",
    hqCountry: "United States",
    region: "North America",
    founded: 2012,
    fundingRaisedUSD: 0,
    valuationOrMarketCapUSD: 0,
    employees: 1,
    status: "Public",
    ticker: "SNOW",
    oneLineDescription: "duplicate; removed at build",
    website: "https://www.snowflake.com",
    dataSource: "dupe",
    asOfDate: SNAP,
  },
  {
    name: "EvenUp",
    sector: "Enterprise AI",
    subsector: "Personal injury AI",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2019,
    fundingRaisedUSD: 107_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 250,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Automates legal demand letters and medical chronologies for personal-injury firms.",
    website: "https://www.evenuplaw.com",
    dataSource: "Crunchbase / Forbes AI 50",
    asOfDate: "2024-05",
  },
  {
    name: "Aidyia",
    sector: "Fintech",
    subsector: "AI hedge fund",
    hqCity: "Hong Kong",
    hqCountry: "China",
    region: "Asia-Pacific",
    founded: 2014,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: null,
    employees: 50,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Early AGI-driven quantitative trading firm; figures not publicly disclosed.",
    website: "https://aidyia.com",
    dataSource: "Press (estimate; figures undisclosed)",
    asOfDate: "2024-01",
  },
  {
    name: "Kensho",
    sector: "Fintech",
    subsector: "Financial analytics AI",
    hqCity: "Cambridge",
    hqCountry: "United States",
    region: "North America",
    founded: 2013,
    fundingRaisedUSD: 174_000_000,
    valuationOrMarketCapUSD: 700_000_000,
    employees: 300,
    status: "Acquired",
    ticker: null,
    oneLineDescription:
      "Analytics and AI platform for financial markets, acquired by S&P Global in 2018.",
    website: "https://kensho.com",
    dataSource: "S&P Global / Crunchbase (acquired)",
    asOfDate: "2018-03",
  },
  {
    name: "Upstage",
    sector: "Foundation Models",
    subsector: "Korean LLMs / Solar",
    hqCity: "Seoul",
    hqCountry: "South Korea",
    region: "Asia-Pacific",
    founded: 2020,
    fundingRaisedUSD: 110_000_000,
    valuationOrMarketCapUSD: 600_000_000,
    employees: 150,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Korean AI lab behind the Solar Pro LLM and enterprise document AI.",
    website: "https://www.upstage.ai",
    dataSource: "Crunchbase / press",
    asOfDate: "2024-06",
  },
  {
    name: "Klarna",
    sector: "Fintech",
    subsector: "BNPL + AI customer service",
    hqCity: "Stockholm",
    hqCountry: "Sweden",
    region: "Europe",
    founded: 2005,
    fundingRaisedUSD: 4_000_000_000,
    valuationOrMarketCapUSD: 14_600_000_000,
    employees: 5000,
    status: "Public",
    ticker: "KLAR",
    oneLineDescription:
      "BNPL fintech that publicly replaced large swaths of customer service with an OpenAI-powered assistant.",
    website: "https://www.klarna.com",
    dataSource: "IPO coverage / Yahoo Finance, market cap",
    asOfDate: SNAP,
  },
  {
    name: "Saronic", // dupe guard — removed at build
    sector: "Autonomous Systems & Robotics",
    subsector: "dupe",
    hqCity: "Austin",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 0,
    valuationOrMarketCapUSD: 0,
    employees: 1,
    status: "Private",
    ticker: null,
    oneLineDescription: "duplicate; removed at build",
    website: "https://www.saronic.com",
    dataSource: "dupe",
    asOfDate: SNAP,
  },
  {
    name: "H",
    sector: "Foundation Models",
    subsector: "Action models / agents",
    hqCity: "Paris",
    hqCountry: "France",
    region: "Europe",
    founded: 2024,
    fundingRaisedUSD: 220_000_000,
    valuationOrMarketCapUSD: 1_100_000_000,
    employees: 50,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Paris startup building agentic 'action' models for enterprise automation.",
    website: "https://www.hcompany.ai",
    dataSource: "Reuters / Crunchbase, seed round",
    asOfDate: "2024-05",
  },
  {
    name: "Tome",
    sector: "Media & Creativity",
    subsector: "AI presentations",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2020,
    fundingRaisedUSD: 105_000_000,
    valuationOrMarketCapUSD: 600_000_000,
    employees: 80,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI tool that generates and edits presentation decks from a prompt.",
    website: "https://tome.app",
    dataSource: "Crunchbase / Forbes AI 50",
    asOfDate: "2024-03",
  },
  {
    name: "Adept", // dupe guard — removed at build
    sector: "Developer Tools",
    subsector: "dupe",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 0,
    valuationOrMarketCapUSD: 0,
    employees: 1,
    status: "Acquired",
    ticker: null,
    oneLineDescription: "duplicate; removed at build",
    website: "https://www.adept.ai",
    dataSource: "dupe",
    asOfDate: SNAP,
  },
  {
    name: "Cursor",
    sector: "Developer Tools",
    subsector: "dupe — see Anysphere",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2022,
    fundingRaisedUSD: 0,
    valuationOrMarketCapUSD: 0,
    employees: 1,
    status: "Private",
    ticker: null,
    oneLineDescription: "duplicate; removed at build",
    website: "https://cursor.com",
    dataSource: "dupe",
    asOfDate: SNAP,
  },
  {
    name: "Tractable",
    sector: "Enterprise AI",
    subsector: "AI insurance claims",
    hqCity: "London",
    hqCountry: "United Kingdom",
    region: "Europe",
    founded: 2014,
    fundingRaisedUSD: 119_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 300,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Computer-vision AI that assesses vehicle and property damage for insurance claims.",
    website: "https://tractable.ai",
    dataSource: "Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Synthetic Minds", // placeholder removed at build
    sector: "Other",
    subsector: "dupe",
    hqCity: "n/a",
    hqCountry: "n/a",
    region: "North America",
    founded: 2020,
    fundingRaisedUSD: 0,
    valuationOrMarketCapUSD: 0,
    employees: 1,
    status: "Private",
    ticker: null,
    oneLineDescription: "duplicate; removed at build",
    website: "https://example.com",
    dataSource: "dupe",
    asOfDate: SNAP,
  },
  {
    name: "Vention",
    sector: "Other",
    subsector: "AI engineering services",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2002,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: null,
    employees: 13000,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Software engineering firm; not an AI company — included for completeness then filtered.",
    website: "https://vention.com",
    dataSource: "test",
    asOfDate: SNAP,
  },
  {
    name: "Cloudera",
    sector: "AI Infrastructure",
    subsector: "Hybrid data + ML",
    hqCity: "Santa Clara",
    hqCountry: "United States",
    region: "North America",
    founded: 2008,
    fundingRaisedUSD: 1_900_000_000,
    valuationOrMarketCapUSD: 5_300_000_000,
    employees: 3000,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Hybrid data platform for enterprise ML and analytics on private cloud.",
    website: "https://www.cloudera.com",
    dataSource: "Crunchbase (post-take-private)",
    asOfDate: "2024-01",
  },
  {
    name: "DataRobot",
    sector: "Enterprise AI",
    subsector: "AutoML platform",
    hqCity: "Boston",
    hqCountry: "United States",
    region: "North America",
    founded: 2012,
    fundingRaisedUSD: 1_200_000_000,
    valuationOrMarketCapUSD: 2_700_000_000,
    employees: 1500,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "End-to-end platform for building, deploying, and governing machine-learning models.",
    website: "https://www.datarobot.com",
    dataSource: "Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Dataiku",
    sector: "Enterprise AI",
    subsector: "Everyday AI platform",
    hqCity: "Paris",
    hqCountry: "France",
    region: "Europe",
    founded: 2013,
    fundingRaisedUSD: 846_000_000,
    valuationOrMarketCapUSD: 4_600_000_000,
    employees: 1200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Collaborative platform that lets both coders and analysts build and deploy ML/AI.",
    website: "https://www.dataiku.com",
    dataSource: "Crunchbase, Series F",
    asOfDate: "2024-12",
  },
  {
    name: "Pinecone",
    sector: "AI Infrastructure",
    subsector: "Vector database",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2019,
    fundingRaisedUSD: 138_000_000,
    valuationOrMarketCapUSD: 750_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Managed vector database widely used as the retrieval layer for RAG applications.",
    website: "https://www.pinecone.io",
    dataSource: "Crunchbase / Forbes AI 50",
    asOfDate: "2024-04",
  },
  {
    name: "Snorkel AI",
    sector: "AI Infrastructure",
    subsector: "Programmatic data labeling",
    hqCity: "Palo Alto",
    hqCountry: "United States",
    region: "North America",
    founded: 2019,
    fundingRaisedUSD: 135_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Programmatic data-labeling (weak supervision) platform to train custom models faster.",
    website: "https://www.snorkel.ai",
    dataSource: "Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Weights & Biases",
    sector: "AI Infrastructure",
    subsector: "ML MLOps platform",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2017,
    fundingRaisedUSD: 250_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 350,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Experiment tracking, evals, and model management used across the AI research community.",
    website: "https://wandb.ai",
    dataSource: "Crunchbase",
    asOfDate: "2023-09",
  },
  {
    name: "Modal",
    sector: "AI Infrastructure",
    subsector: "Serverless GPU compute",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2021,
    fundingRaisedUSD: 100_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 90,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Serverless cloud for running AI inference and training jobs from Python.",
    website: "https://modal.com",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-06",
  },
  {
    name: "Replicate",
    sector: "AI Infrastructure",
    subsector: "Model hosting / inference",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2019,
    fundingRaisedUSD: 60_000_000,
    valuationOrMarketCapUSD: 350_000_000,
    employees: 60,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Run and fine-tune thousands of open models via a simple API.",
    website: "https://replicate.com",
    dataSource: "Crunchbase",
    asOfDate: "2023-08",
  },
  {
    name: "Krutrim",
    sector: "Foundation Models",
    subsector: "India-centric LLMs",
    hqCity: "Bengaluru",
    hqCountry: "India",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 70_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 200,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "India's first AI unicorn, building Indic-language foundation models.",
    website: "https://krutrim.ai",
    dataSource: "Reuters / Crunchbase",
    asOfDate: "2024-01",
  },
  {
    name: "Sarvam AI",
    sector: "Foundation Models",
    subsector: "Indian voice & Indic LLMs",
    hqCity: "Bengaluru",
    hqCountry: "India",
    region: "Asia-Pacific",
    founded: 2023,
    fundingRaisedUSD: 41_000_000,
    valuationOrMarketCapUSD: null,
    employees: 100,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Builds full-stack Indic voice and text models for the Indian market.",
    website: "https://sarvam.ai",
    dataSource: "TechCrunch / Crunchbase",
    asOfDate: "2024-06",
  },
  {
    name: "Lightricks",
    sector: "Media & Creativity",
    subsector: "Mobile creative AI",
    hqCity: "Jerusalem",
    hqCountry: "Israel",
    region: "Middle East",
    founded: 2013,
    fundingRaisedUSD: 335_000_000,
    valuationOrMarketCapUSD: 1_800_000_000,
    employees: 400,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Maker of Facetune and Photoleap, now adding generative models (LTX) for creators.",
    website: "https://lightricks.com",
    dataSource: "Crunchbase",
    asOfDate: "2023-09",
  },
  {
    name: "Captions",
    sector: "Media & Creativity",
    subsector: "AI video editing",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2020,
    fundingRaisedUSD: 95_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 80,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI-powered camera app that adds captions, eye-contact, and edits to talking-head video.",
    website: "https://www.captions.ai",
    dataSource: "TechCrunch / Forbes AI 50",
    asOfDate: "2024-07",
  },
  {
    name: "HeyGen",
    sector: "Media & Creativity",
    subsector: "AI video avatars",
    hqCity: "Los Angeles",
    hqCountry: "United States",
    region: "North America",
    founded: 2020,
    fundingRaisedUSD: 94_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 100,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Generates lifelike talking-avatar marketing and training videos from text.",
    website: "https://www.heygen.com",
    dataSource: "Forbes AI 50 / Crunchbase",
    asOfDate: "2024-07",
  },
  {
    name: "Crusoe",
    sector: "AI Infrastructure",
    subsector: "Clean-energy GPU cloud",
    hqCity: "Denver",
    hqCountry: "United States",
    region: "North America",
    founded: 2018,
    fundingRaisedUSD: 1_800_000_000,
    valuationOrMarketCapUSD: 3_500_000_000,
    employees: 600,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Operates AI datacenters powered by stranded and renewable energy.",
    website: "https://crusoe.ai",
    dataSource: "Bloomberg / Crunchbase, Series D",
    asOfDate: "2024-12",
  },
  {
    name: "Norm Ai",
    sector: "Enterprise AI",
    subsector: "Regulatory compliance AI",
    hqCity: "New York",
    hqCountry: "United States",
    region: "North America",
    founded: 2023,
    fundingRaisedUSD: 87_000_000,
    valuationOrMarketCapUSD: 250_000_000,
    employees: 80,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Automates corporate regulatory compliance with specialized AI agents.",
    website: "https://norm.ai",
    dataSource: "Forbes AI 50 / Crunchbase",
    asOfDate: "2024-07",
  },
  {
    name: "Qodo",
    sector: "Developer Tools",
    subsector: "AI code quality",
    hqCity: "Tel Aviv",
    hqCountry: "Israel",
    region: "Middle East",
    founded: 2020,
    fundingRaisedUSD: 49_000_000,
    valuationOrMarketCapUSD: 300_000_000,
    employees: 80,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "AI code-quality and test-generation platform (formerly CodiumAI).",
    website: "https://www.qodo.ai",
    dataSource: "Forbes AI 50 / Crunchbase",
    asOfDate: "2024-07",
  },
  {
    name: "Baseten",
    sector: "AI Infrastructure",
    subsector: "Model serving infrastructure",
    hqCity: "San Francisco",
    hqCountry: "United States",
    region: "North America",
    founded: 2019,
    fundingRaisedUSD: 100_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 80,
    status: "Private",
    ticker: null,
    oneLineDescription:
      "Serverless infrastructure for deploying and scaling ML models in production.",
    website: "https://baseten.co",
    dataSource: "Crunchbase",
    asOfDate: "2024-06",
  },
  {
    name: "Roblox",
    sector: "Media & Creativity",
    subsector: "Generative tools for UGC",
    hqCity: "San Mateo",
    hqCountry: "United States",
    region: "North America",
    founded: 2004,
    fundingRaisedUSD: 924_000_000,
    valuationOrMarketCapUSD: 70_000_000_000,
    employees: 2800,
    status: "Public",
    ticker: "RBLX",
    oneLineDescription:
      "UGC gaming platform investing heavily in generative tools for creators.",
    website: "https://www.roblox.com",
    dataSource: "Yahoo Finance, market cap",
    asOfDate: SNAP,
  },
];

// ─── Build: dedupe, filter, rank, write ────────────────────────────────────

const SECTORS: Sector[] = [
  "Foundation Models",
  "AI Infrastructure",
  "Enterprise AI",
  "Healthcare & Life Sciences",
  "Fintech",
  "Autonomous Systems & Robotics",
  "Cybersecurity",
  "Developer Tools",
  "AI Hardware",
  "Media & Creativity",
  "Education",
  "Other",
];
const REGIONS: Region[] = [
  "North America",
  "Europe",
  "Asia-Pacific",
  "Middle East",
  "Latin America",
  "Africa",
];
const STATUSES = ["Private", "Public", "Acquired", "Defunct"] as const;

function assertValid(c: Company) {
  if (!SECTORS.includes(c.sector)) throw new Error(`${c.name}: bad sector ${c.sector}`);
  if (!REGIONS.includes(c.region)) throw new Error(`${c.name}: bad region ${c.region}`);
  if (!STATUSES.includes(c.status)) throw new Error(`${c.name}: bad status ${c.status}`);
  if (typeof c.founded !== "number" || c.founded < 1970 || c.founded > 2026)
    throw new Error(`${c.name}: bad founded ${c.founded}`);
}

function main() {
  // dedupe by canonical name, dropping intentional dummies ("dupe", placeholders, non-AI test)
  const seen = new Set<string>();
  const keep: Company[] = [];
  for (const c of COMPANIES) {
    if (c.subsector === "dupe" || c.subsector.startsWith("dupe")) continue;
    if (c.dataSource === "dupe") continue;
    if (c.dataSource === "test") continue;
    if (c.oneLineDescription.includes("not an AI company")) continue;
    const key = c.name.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    assertValid(c);
    keep.push(c);
  }

  // rank: valuation desc, then funding desc, then name asc
  keep.sort((a, b) => {
    const va = a.valuationOrMarketCapUSD ?? 0;
    const vb = b.valuationOrMarketCapUSD ?? 0;
    if (vb !== va) return vb - va;
    const fa = a.fundingRaisedUSD ?? 0;
    const fb = b.fundingRaisedUSD ?? 0;
    if (fb !== fa) return fb - fa;
    return a.name.localeCompare(b.name);
  });

  const ranked = keep.map((c, i) => ({ ...c, rank: i + 1 }));

  // trim to 100 if we overshoot
  const final = ranked.slice(0, 100);

  console.log(
    `Built ${final.length} companies. ` +
      `Public: ${final.filter((c) => c.status === "Public").length}, ` +
      `Private: ${final.filter((c) => c.status === "Private").length}, ` +
      `Acquired: ${final.filter((c) => c.status === "Acquired").length}.`,
  );
  console.log(
    `Total capital tracked: $${(
      final.reduce((s, c) => s + (c.valuationOrMarketCapUSD ?? 0), 0) / 1e12
    ).toFixed(2)}T`,
  );
  console.log(`Countries: ${new Set(final.map((c) => c.hqCountry)).size}`);
  console.log(`Sectors: ${new Set(final.map((c) => c.sector)).size}`);
}

main();
