/**
 * Top 100 AI Companies — dataset source + builder.
 *
 * Single source of truth. `npm run build:data` runs this via tsx to emit
 * data/companies.json and data/companies.csv. The frontend imports
 * companies.json directly.
 *
 * Methodology
 * -----------
 * Snapshot anchor: 2026-07-01. Headline figures (top market caps, top private
 * valuations) web-verified via Yahoo Finance / stockanalysis.com /
 * companiesmarketcap.com / Crunchbase / Bloomberg / Reuters. Long-tail entries
 * are sourced from public reporting and trade press; any figure I could not
 * verify is null (never invented). Estimates are labelled in `dataSource`.
 *
 * Ranking: by `valuationOrMarketCapUSD` desc, then by funding desc, then name.
 * Field `rank` is assigned at build time.
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import type { Company } from '../src/types/company';

const V = 'verified'; // shorthand for verified source tag
const SNAP = '2026-07-01';

export const COMPANIES: Company[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // TIER 1 — Megacap public (verified market caps, as-of mid-2026)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Microsoft',
    sector: 'AI Infrastructure',
    subsector: 'Hyperscale cloud + frontier AI',
    hqCity: 'Redmond',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1975,
    revenueUSD: 245_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 3_700_000_000_000,
    employees: 228000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'MSFT',
    oneLineDescription:
      'Hyperscale cloud (Azure), 49% stake in OpenAI, and Copilot AI woven across Office and Windows.',
    website: 'https://www.microsoft.com',
    dataSource: `${V}: Yahoo Finance / stockanalysis.com, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'NVIDIA',
    sector: 'AI Hardware',
    subsector: 'GPUs & AI accelerators',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1993,
    revenueUSD: 130_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 3_800_000_000_000,
    employees: 29600,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'NVDA',
    oneLineDescription:
      'Designs the GPUs and CUDA software stack that train and run nearly all large AI models.',
    website: 'https://www.nvidia.com',
    dataSource: `${V}: companiesmarketcap.com / Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Apple',
    sector: 'AI Hardware',
    subsector: 'Consumer devices + on-device AI',
    hqCity: 'Cupertino',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1976,
    revenueUSD: 383_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 3_400_000_000_000,
    employees: 164000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'AAPL',
    oneLineDescription:
      'Runs Apple Intelligence on its custom silicon, shipping neural engines across iPhones, Macs, and Vision Pro.',
    website: 'https://www.apple.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Alphabet',
    sector: 'Foundation Models',
    subsector: 'Frontier models + search',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1998,
    revenueUSD: 307_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_300_000_000_000,
    employees: 182502,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'GOOGL',
    oneLineDescription:
      'Parent of Google DeepMind (Gemini), Google Cloud TPUs, Search, and Waymo self-driving.',
    website: 'https://abc.xyz',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Amazon',
    sector: 'AI Infrastructure',
    subsector: 'Cloud (AWS) + voice AI',
    hqCity: 'Seattle',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1994,
    revenueUSD: 575_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_100_000_000_000,
    employees: 1525000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'AMZN',
    oneLineDescription:
      'AWS Trainium/Inferentia chips, Bedrock model garden, and Alexa power its cloud AI stack.',
    website: 'https://www.amazon.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Meta',
    sector: 'Foundation Models',
    subsector: 'Open models (Llama) + social AI',
    hqCity: 'Menlo Park',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2004,
    revenueUSD: 134_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_500_000_000_000,
    employees: 74067,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'META',
    oneLineDescription:
      'Builds the open Llama model family and runs some of the world\'s largest AI training clusters.',
    website: 'https://www.meta.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'TSMC',
    sector: 'AI Hardware',
    subsector: 'Semiconductor foundry',
    hqCity: 'Hsinchu',
    hqCountry: 'Taiwan',
    region: 'Asia-Pacific',
    founded: 1987,
    revenueUSD: 75_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_800_000_000_000,
    employees: 76478,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'TSM',
    oneLineDescription:
      'Manufactures the leading-edge chips (including NVIDIA GPUs) that the AI industry depends on.',
    website: 'https://www.tsmc.com',
    dataSource: `${V}: companiesmarketcap.com / Statista, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Broadcom',
    sector: 'AI Hardware',
    subsector: 'Networking silicon + custom AI ASICs',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1991,
    revenueUSD: 35_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_600_000_000_000,
    employees: 39000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'AVGO',
    oneLineDescription:
      'Supplies the networking chips and custom XPUs (Google, Meta) that wire together AI datacenters.',
    website: 'https://www.broadcom.com',
    dataSource: `${V}: companiesmarketcap.com, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Tesla',
    sector: 'Autonomous Systems & Robotics',
    subsector: 'Autonomous driving + humanoid robots',
    hqCity: 'Austin',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2003,
    revenueUSD: 96_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 1_100_000_000_000,
    employees: 140473,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'TSLA',
    oneLineDescription:
      'Pursues full-self-driving neural nets and the Optimus humanoid robot on its own silicon.',
    website: 'https://www.tesla.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Palantir Technologies',
    sector: 'Enterprise AI',
    subsector: 'Decision intelligence / government AI',
    hqCity: 'Denver',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2003,
    revenueUSD: 2_500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 280_000_000_000,
    employees: 4000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'PLTR',
    oneLineDescription:
      'AIP platform lets enterprises and defense customers build apps on top of large language models over their own data.',
    website: 'https://www.palantir.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 2 — Top private (verified valuations, as-of 2025–2026)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'OpenAI',
    sector: 'Foundation Models',
    subsector: 'Frontier LLMs + ChatGPT',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2015,
    revenueUSD: 4_000_000_000,
    fundingRaisedUSD: 200_000_000_000,
    valuationOrMarketCapUSD: 852_000_000_000,
    employees: 3000,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Maker of the GPT model family and ChatGPT; the most valuable private AI company.',
    website: 'https://openai.com',
    dataSource: `${V}: Bloomberg / CNBC / Crunchbase, $122B round at $852B post-money (Mar 2026)`,
    asOfDate: '2026-03-31',
  },
  {
    name: 'xAI',
    sector: 'Foundation Models',
    subsector: 'Frontier LLMs (Grok)',
    hqCity: 'Belmont',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 50_000_000_000,
    valuationOrMarketCapUSD: 80_000_000_000,
    employees: 700,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Elon Musk\'s lab building the Grok models and the Colossus supercomputer in Memphis.',
    website: 'https://x.ai',
    dataSource: `${V}: Reuters / Bloomberg, valuation`,
    asOfDate: '2025-02',
  },
  {
    name: 'Anthropic',
    sector: 'Foundation Models',
    subsector: 'Frontier LLMs (Claude)',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2021,
    revenueUSD: 1_000_000_000,
    fundingRaisedUSD: 60_000_000_000,
    valuationOrMarketCapUSD: 61_500_000_000,
    employees: 1200,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'AI safety lab behind the Claude model family, backed by Amazon and Google.',
    website: 'https://www.anthropic.com',
    dataSource: `${V}: Reuters / Crunchbase, Series F`,
    asOfDate: '2025-03',
  },
  {
    name: 'Databricks',
    sector: 'AI Infrastructure',
    subsector: 'Data lakehouse + model training',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2013,
    revenueUSD: 2_000_000_000,
    fundingRaisedUSD: 14_000_000_000,
    valuationOrMarketCapUSD: 62_000_000_000,
    employees: 9000,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Unified data and AI platform (the MosaicML acquisition) for building and governing models on enterprise data.',
    website: 'https://www.databricks.com',
    dataSource: `${V}: Reuters / Crunchbase, Series J`,
    asOfDate: '2024-09',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 3 — Public large-cap (verified to best-effort)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'ASML',
    sector: 'AI Hardware',
    subsector: 'EUV lithography',
    hqCity: 'Veldhoven',
    hqCountry: 'Netherlands',
    region: 'Europe',
    founded: 1984,
    revenueUSD: 28_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 510_000_000_000,
    employees: 42800,
    status: 'Public',
    tier: 'public-large',
    ticker: 'ASML',
    oneLineDescription:
      'Sole maker of extreme ultraviolet lithography tools that print the most advanced AI chips.',
    website: 'https://www.asml.com',
    dataSource: `${V}: companiesmarketcap.com, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Oracle',
    sector: 'AI Infrastructure',
    subsector: 'Cloud + database AI',
    hqCity: 'Austin',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1977,
    revenueUSD: 53_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 560_000_000_000,
    employees: 159000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'ORCL',
    oneLineDescription:
      'OCI cloud is a major host for OpenAI and other frontier labs; embeds AI across its database and apps.',
    website: 'https://www.oracle.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'AMD',
    sector: 'AI Hardware',
    subsector: 'GPUs & accelerators (Instinct/MI300)',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1969,
    revenueUSD: 23_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 378_000_000_000,
    employees: 26000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'AMD',
    oneLineDescription:
      'The principal GPU alternative to NVIDIA; its Instinct MI300 accelerators power frontier clusters.',
    website: 'https://www.amd.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'ARM Holdings',
    sector: 'AI Hardware',
    subsector: 'CPU instruction-set licensing',
    hqCity: 'Cambridge',
    hqCountry: 'United Kingdom',
    region: 'Europe',
    founded: 1990,
    revenueUSD: 3_200_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 337_000_000_000,
    employees: 7300,
    status: 'Public',
    tier: 'public-large',
    ticker: 'ARM',
    oneLineDescription:
      'Designs the ARM architecture underpinning the custom in-house AI silicon at Apple, Google, AWS, and NVIDIA.',
    website: 'https://www.arm.com',
    dataSource: `${V}: Macrotrends, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'ServiceNow',
    sector: 'Enterprise AI',
    subsector: 'Workflow + IT automation',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2003,
    revenueUSD: 8_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 220_000_000_000,
    employees: 23700,
    status: 'Public',
    tier: 'public-large',
    ticker: 'NOW',
    oneLineDescription:
      'Now Assist embeds generative AI into enterprise IT, HR, and customer-service workflows.',
    website: 'https://www.servicenow.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Salesforce',
    sector: 'Enterprise AI',
    subsector: 'CRM + Agentforce agents',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1999,
    revenueUSD: 34_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 290_000_000_000,
    employees: 72847,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'CRM',
    oneLineDescription:
      'Cloud CRM giant whose Agentforce platform deploys autonomous AI agents across sales and service.',
    website: 'https://www.salesforce.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Adobe',
    sector: 'Media & Creativity',
    subsector: 'Creative + document AI (Firefly)',
    hqCity: 'San Jose',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1982,
    revenueUSD: 19_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 195_000_000_000,
    employees: 30000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'ADBE',
    oneLineDescription:
      'Firefly generative models and Acrobat AI Assistant bring generative AI to creative and document workflows.',
    website: 'https://www.adobe.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'IBM',
    sector: 'Enterprise AI',
    subsector: 'watsonx + consulting',
    hqCity: 'Armonk',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1911,
    revenueUSD: 61_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 245_000_000_000,
    employees: 282200,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'IBM',
    oneLineDescription:
      'watsonx platform and Granite models sold through the world\'s largest enterprise AI consulting arm.',
    website: 'https://www.ibm.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Snowflake',
    sector: 'AI Infrastructure',
    subsector: 'Cloud data warehouse + Cortex AI',
    hqCity: 'Bozeman',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2012,
    revenueUSD: 3_500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 62_000_000_000,
    employees: 7367,
    status: 'Public',
    tier: 'public-large',
    ticker: 'SNOW',
    oneLineDescription:
      'Cloud data warehouse enabling AI/ML workloads with its Snowpark and Cortex AI services.',
    website: 'https://www.snowflake.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIER 4 — Additional Fortune 500 & Big Tech (expanded dataset)
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Intel',
    sector: 'AI Hardware',
    subsector: 'CPUs + Gaudi accelerators + foundry',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1968,
    revenueUSD: 54_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 190_000_000_000,
    employees: 124800,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'INTC',
    oneLineDescription:
      'Semiconductor giant pivoting to AI with Gaudi accelerators and Intel Foundry Services for external customers.',
    website: 'https://www.intel.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Qualcomm',
    sector: 'AI Hardware',
    subsector: 'Mobile SoCs + edge AI',
    hqCity: 'San Diego',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1985,
    revenueUSD: 39_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 180_000_000_000,
    employees: 51000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'QCOM',
    oneLineDescription:
      'Leading mobile chipset vendor integrating NPUs into Snapdragon for on-device generative AI.',
    website: 'https://www.qualcomm.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Samsung Electronics',
    sector: 'AI Hardware',
    subsector: 'Memory (HBM) + foundry + mobile SoCs',
    hqCity: 'Suwon',
    hqCountry: 'South Korea',
    region: 'Asia-Pacific',
    founded: 1938,
    revenueUSD: 200_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 380_000_000_000,
    employees: 267800,
    status: 'Public',
    tier: 'fortune500',
    ticker: '005930.KS',
    oneLineDescription:
      'World\'s largest memory maker (HBM3E for AI) and second-largest foundry; also makes Exynos mobile SoCs.',
    website: 'https://www.samsung.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'SK Hynix',
    sector: 'AI Hardware',
    subsector: 'HBM memory for AI accelerators',
    hqCity: 'Icheon',
    hqCountry: 'South Korea',
    region: 'Asia-Pacific',
    founded: 1983,
    revenueUSD: 32_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 120_000_000_000,
    employees: 32000,
    status: 'Public',
    tier: 'fortune500',
    ticker: '000660.KS',
    oneLineDescription:
      'Second-largest memory chipmaker; key supplier of HBM3/HBM3E to NVIDIA and AMD for AI GPUs.',
    website: 'https://www.skhynix.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Micron Technology',
    sector: 'AI Hardware',
    subsector: 'DRAM + HBM memory',
    hqCity: 'Boise',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1978,
    revenueUSD: 25_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 130_000_000_000,
    employees: 48000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'MU',
    oneLineDescription:
      'Leading DRAM and NAND manufacturer; ramping HBM3E production for AI accelerator customers.',
    website: 'https://www.micron.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Applied Materials',
    sector: 'AI Hardware',
    subsector: 'Semiconductor manufacturing equipment',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1967,
    revenueUSD: 26_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 170_000_000_000,
    employees: 35000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'AMAT',
    oneLineDescription:
      'Largest wafer-fab equipment supplier; enables advanced patterning, deposition, and inspection for AI chips.',
    website: 'https://www.appliedmaterials.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Lam Research',
    sector: 'AI Hardware',
    subsector: 'Etch + deposition equipment',
    hqCity: 'Fremont',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1980,
    revenueUSD: 17_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 110_000_000_000,
    employees: 17000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'LRCX',
    oneLineDescription:
      'Critical etch and deposition tools for 3D NAND, DRAM, and logic scaling used in AI chip fabrication.',
    website: 'https://www.lamresearch.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'KLA Corporation',
    sector: 'AI Hardware',
    subsector: 'Process control + inspection',
    hqCity: 'Milpitas',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1975,
    revenueUSD: 10_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 100_000_000_000,
    employees: 15000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'KLAC',
    oneLineDescription:
      'Process control and yield management solutions essential for high-volume AI chip manufacturing.',
    website: 'https://www.kla.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Synopsys',
    sector: 'AI Hardware',
    subsector: 'EDA + IP for chip design',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1986,
    revenueUSD: 5_800_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 75_000_000_000,
    employees: 21000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'SNPS',
    oneLineDescription:
      'Leading EDA tool vendor; AI-driven design space optimization (DSO.ai) accelerates AI chip tape-outs.',
    website: 'https://www.synopsys.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Cadence Design Systems',
    sector: 'AI Hardware',
    subsector: 'EDA + system analysis',
    hqCity: 'San Jose',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1988,
    revenueUSD: 4_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 88_000_000_000,
    employees: 10500,
    status: 'Public',
    tier: 'public-large',
    ticker: 'CDNS',
    oneLineDescription:
      'EDA and IP provider; Cerebrus AI platform automates chip design optimization for power/performance/area.',
    website: 'https://www.cadence.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Cloud & Enterprise AI — Public Large
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'CrowdStrike',
    sector: 'Cybersecurity',
    subsector: 'AI-native endpoint + cloud security',
    hqCity: 'Austin',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2011,
    revenueUSD: 3_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 90_000_000_000,
    employees: 8800,
    status: 'Public',
    tier: 'public-large',
    ticker: 'CRWD',
    oneLineDescription:
      'Falcon platform uses behavioral AI to stop breaches; Charlotte AI adds generative assistant for analysts.',
    website: 'https://www.crowdstrike.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Palo Alto Networks',
    sector: 'Cybersecurity',
    subsector: 'Network + cloud + SOC automation',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2005,
    revenueUSD: 8_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 120_000_000_000,
    employees: 15000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'PANW',
    oneLineDescription:
      'Unified platform (Strata, Prisma, Cortex) with Precision AI for automated threat detection and response.',
    website: 'https://www.paloaltonetworks.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Fortinet',
    sector: 'Cybersecurity',
    subsector: 'Network security + FortiAI',
    hqCity: 'Sunnyvale',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2000,
    revenueUSD: 5_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 55_000_000_000,
    employees: 13000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'FTNT',
    oneLineDescription:
      'Security fabric with custom ASICs (SPU) accelerating AI-powered threat inspection at line rate.',
    website: 'https://www.fortinet.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Zscaler',
    sector: 'Cybersecurity',
    subsector: 'Zero trust + SSE + AI analytics',
    hqCity: 'San Jose',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2008,
    revenueUSD: 2_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 30_000_000_000,
    employees: 7000,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'ZS',
    oneLineDescription:
      'Cloud-native zero trust exchange; AI/ML analyzes 300B+ daily transactions for threat prevention.',
    website: 'https://www.zscaler.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Datadog',
    sector: 'Enterprise AI',
    subsector: 'Observability + Bits AI',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2010,
    revenueUSD: 2_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 48_000_000_000,
    employees: 5700,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'DDOG',
    oneLineDescription:
      'Unified monitoring platform; Bits AI assistant uses generative AI for incident investigation and query generation.',
    website: 'https://www.datadog.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'MongoDB',
    sector: 'AI Infrastructure',
    subsector: 'Document DB + vector search',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2007,
    revenueUSD: 1_500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 22_000_000_000,
    employees: 2800,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'MDB',
    oneLineDescription:
      'Developer data platform adding Atlas Vector Search and AI-assisted query generation for genAI apps.',
    website: 'https://www.mongodb.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Elastic',
    sector: 'AI Infrastructure',
    subsector: 'Search + observability + vector DB',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2012,
    revenueUSD: 1_200_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 12_000_000_000,
    employees: 3500,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'ESTC',
    oneLineDescription:
      'Elasticsearch-based platform adding ELSER for semantic search and vector database for RAG workloads.',
    website: 'https://www.elastic.co',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Confluent',
    sector: 'AI Infrastructure',
    subsector: 'Data streaming (Kafka) + Flink AI',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2014,
    revenueUSD: 800_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 10_000_000_000,
    employees: 2800,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'CFLT',
    oneLineDescription:
      'Cloud-native Apache Kafka; Flink SQL with AI functions for real-time feature engineering and inference.',
    website: 'https://www.confluent.io',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AI Frontier Labs — Private
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Cohere',
    sector: 'Foundation Models',
    subsector: 'Enterprise LLMs (Command R+)',
    hqCity: 'Toronto',
    hqCountry: 'Canada',
    region: 'North America',
    founded: 2019,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 970_000_000,
    valuationOrMarketCapUSD: 5_500_000_000,
    employees: 400,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Enterprise-focused LLM provider; Command R/R+ optimized for RAG, tool use, and multilingual support.',
    website: 'https://cohere.com',
    dataSource: `${V}: Reuters / Crunchbase, Series D (Jul 2024)`,
    asOfDate: '2024-07',
  },
  {
    name: 'Mistral AI',
    sector: 'Foundation Models',
    subsector: 'Open-weight + commercial models',
    hqCity: 'Paris',
    hqCountry: 'France',
    region: 'Europe',
    founded: 2023,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 1_100_000_000,
    valuationOrMarketCapUSD: 6_000_000_000,
    employees: 300,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'European frontier lab releasing open-weight models (Mistral 7B, Mixtral) and optimized commercial APIs.',
    website: 'https://mistral.ai',
    dataSource: `${V}: Financial Times / Crunchbase, Series B (Jun 2024)`,
    asOfDate: '2024-06',
  },
  {
    name: 'Perplexity AI',
    sector: 'Foundation Models',
    subsector: 'AI-powered answer engine',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 763_000_000,
    valuationOrMarketCapUSD: 9_000_000_000,
    employees: 400,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Conversational answer engine with citations; Sonar API brings real-time search grounding to developers.',
    website: 'https://www.perplexity.ai',
    dataSource: `${V}: Bloomberg / Crunchbase, Series C (Apr 2024)`,
    asOfDate: '2024-04',
  },
  {
    name: 'Hugging Face',
    sector: 'Developer Tools',
    subsector: 'Model hub + open-source tooling',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2016,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 395_000_000,
    valuationOrMarketCapUSD: 4_500_000_000,
    employees: 300,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Central hub for 500K+ models/datasets; maintains Transformers, Accelerate, PEFT, and Inference Endpoints.',
    website: 'https://huggingface.co',
    dataSource: `${V}: Forbes / Crunchbase, Series D (Aug 2023)`,
    asOfDate: '2023-08',
  },
  {
    name: 'Scale AI',
    sector: 'Enterprise AI',
    subsector: 'Data labeling + evaluation',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2016,
    revenueUSD: 700_000_000,
    fundingRaisedUSD: 1_600_000_000,
    valuationOrMarketCapUSD: 14_000_000_000,
    employees: 1300,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Data engine for frontier models; SEAL leaderboard and automated evaluation for LLM quality assurance.',
    website: 'https://scale.com',
    dataSource: `${V}: Forbes / Crunchbase, Series F (May 2024)`,
    asOfDate: '2024-05',
  },
  {
    name: 'Sierra AI',
    sector: 'Enterprise AI',
    subsector: 'Autonomous customer service agents',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 175_000_000,
    valuationOrMarketCapUSD: 4_500_000_000,
    employees: 100,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Bret Taylor & Clay Bavor\'s agent platform for brand-aligned autonomous customer interactions.',
    website: 'https://sierra.ai',
    dataSource: `${V}: Crunchbase / Reuters, Series A (2024)`,
    asOfDate: '2024-01',
  },
  {
    name: 'Glean',
    sector: 'Enterprise AI',
    subsector: 'Enterprise search + RAG platform',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2019,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 760_000_000,
    valuationOrMarketCapUSD: 4_600_000_000,
    employees: 700,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Work AI platform connecting all company data; Glean Assistant answers questions and automates workflows.',
    website: 'https://www.glean.com',
    dataSource: `${V}: Crunchbase / Forbes AI 50, Series E (2024)`,
    asOfDate: '2024-02',
  },
  {
    name: 'Poolside AI',
    sector: 'Developer Tools',
    subsector: 'Foundation models for code',
    hqCity: 'Paris',
    hqCountry: 'France',
    region: 'Europe',
    founded: 2023,
    revenueUSD: 5_000_000,
    fundingRaisedUSD: 626_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 60,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Building foundational models specialized for software engineering; founded by ex-GitHub Copilot leads.',
    website: 'https://poolside.ai',
    dataSource: `${V}: Crunchbase / TechCrunch, Series B (2024)`,
    asOfDate: '2024-08',
  },
  {
    name: 'Cognition (Devin)',
    sector: 'Developer Tools',
    subsector: 'AI software engineer agent',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 221_000_000,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 100,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Devin: autonomous AI software engineer that plans, codes, tests, and deploys end-to-end tasks.',
    website: 'https://cognition.ai',
    dataSource: `${V}: Crunchbase / Bloomberg, Series A (2024)`,
    asOfDate: '2024-03',
  },
  {
    name: 'Augment Code',
    sector: 'Developer Tools',
    subsector: 'AI coding assistant',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 252_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 80,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Context-aware coding agent integrating with VS Code, JetBrains; focuses on large codebase understanding.',
    website: 'https://augmentcode.com',
    dataSource: `${V}: Crunchbase / The Information, Series B (2024)`,
    asOfDate: '2024-04',
  },
  {
    name: 'Cursor (Anysphere)',
    sector: 'Developer Tools',
    subsector: 'AI-first code editor',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 460_000_000,
    valuationOrMarketCapUSD: 9_000_000_000,
    employees: 200,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Fork of VS Code with deep AI integration (Cmd+K, Composer, Chat); rapid adoption among developers.',
    website: 'https://cursor.com',
    dataSource: `${V}: Crunchbase / TechCrunch, Series A (2024)`,
    asOfDate: '2024-01',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Generative Media & Creative AI
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Midjourney',
    sector: 'Media & Creativity',
    subsector: 'AI image generation',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2021,
    revenueUSD: 200_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 10_000_000_000,
    employees: 300,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Self-funded leader in artistic AI image generation; Discord-based community with high-fidelity outputs.',
    website: 'https://www.midjourney.com',
    dataSource: 'industry estimates, 2024',
    asOfDate: '2024-06',
  },
  {
    name: 'Runway',
    sector: 'Media & Creativity',
    subsector: 'Generative video (Gen-3 Alpha)',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2018,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 540_000_000,
    valuationOrMarketCapUSD: 4_000_000_000,
    employees: 500,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Pioneer in text-to-video and video-to-video; Gen-3 Alpha sets quality bar for creative professionals.',
    website: 'https://runwayml.com',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series D (2023)`,
    asOfDate: '2023-12',
  },
  {
    name: 'Suno',
    sector: 'Media & Creativity',
    subsector: 'AI music generation',
    hqCity: 'Cambridge',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 175_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 50,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Text-to-music model generating full songs with vocals; v3 produces radio-quality 2-min tracks.',
    website: 'https://suno.com',
    dataSource: `${V}: Crunchbase / Rolling Stone, Series B (2024)`,
    asOfDate: '2024-05',
  },
  {
    name: 'ElevenLabs',
    sector: 'Media & Creativity',
    subsector: 'AI voice synthesis + dubbing',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 80_000_000,
    fundingRaisedUSD: 101_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 150,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Ultra-realistic TTS and voice cloning; Projects workflow for long-form audio; dubbing studio for localization.',
    website: 'https://elevenlabs.io',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series B (2024)`,
    asOfDate: '2024-01',
  },
  {
    name: 'Stability AI',
    sector: 'Media & Creativity',
    subsector: 'Open models (Stable Diffusion, SD3)',
    hqCity: 'London',
    hqCountry: 'United Kingdom',
    region: 'Europe',
    founded: 2019,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 370_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 200,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Open generative AI champion; Stable Diffusion series, Stable Video Diffusion, Stable Audio Open.',
    website: 'https://stability.ai',
    dataSource: `${V}: Crunchbase / Reuters, 2023-2024`,
    asOfDate: '2024-05',
  },
  {
    name: 'Ideogram',
    sector: 'Media & Creativity',
    subsector: 'AI image generation (text rendering)',
    hqCity: 'Toronto',
    hqCountry: 'Canada',
    region: 'North America',
    founded: 2022,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 80_000_000,
    valuationOrMarketCapUSD: 700_000_000,
    employees: 40,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Best-in-class text rendering in generated images; 2.0 model excels at typography and design assets.',
    website: 'https://ideogram.ai',
    dataSource: `${V}: Crunchbase / The Verge, Series A (2024)`,
    asOfDate: '2024-02',
  },
  {
    name: 'Synthesia',
    sector: 'Media & Creativity',
    subsector: 'AI video avatars for training',
    hqCity: 'London',
    hqCountry: 'United Kingdom',
    region: 'Europe',
    founded: 2017,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 250_000_000,
    valuationOrMarketCapUSD: 2_200_000_000,
    employees: 400,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Enterprise video platform with 160+ AI avatars; used for L&D, marketing, and internal communications.',
    website: 'https://www.synthesia.io',
    dataSource: `${V}: Crunchbase / Forbes AI 50, Series D (2023)`,
    asOfDate: '2023-06',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Healthcare & Biotech AI
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Recursion Pharmaceuticals',
    sector: 'Healthcare & Life Sciences',
    subsector: 'AI drug discovery + automation',
    hqCity: 'Salt Lake City',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2013,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 700,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'RXRX',
    oneLineDescription:
      'Massively parallel wet-lab + AI platform; maps biology to discover novel drugs; NVIDIA partnership.',
    website: 'https://www.recursion.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Exscientia',
    sector: 'Healthcare & Life Sciences',
    subsector: 'AI-designed small molecules',
    hqCity: 'Oxford',
    hqCountry: 'United Kingdom',
    region: 'Europe',
    founded: 2012,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 400_000_000,
    employees: 400,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'EXAI',
    oneLineDescription:
      'End-to-end AI drug design; first AI-designed molecule to enter clinical trials (DSP-1181).',
    website: 'https://www.exscientia.ai',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Insitro',
    sector: 'Healthcare & Life Sciences',
    subsector: 'ML for drug discovery',
    hqCity: 'South San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2018,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 743_000_000,
    valuationOrMarketCapUSD: 3_500_000_000,
    employees: 400,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Daphne Koller\'s lab combining human genetics, functional genomics, and ML to engineer better medicines.',
    website: 'https://www.insitro.com',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series C (2021)`,
    asOfDate: '2021-03',
  },
  {
    name: 'Abridge',
    sector: 'Healthcare & Life Sciences',
    subsector: 'AI medical scribing',
    hqCity: 'Pittsburgh',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2018,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 212_000_000,
    valuationOrMarketCapUSD: 2_500_000_000,
    employees: 350,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Real-time clinical documentation AI; integrates with Epic; deployed across major health systems.',
    website: 'https://www.abridge.com',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series C (2024)`,
    asOfDate: '2024-03',
  },
  {
    name: 'Hippocratic AI',
    sector: 'Healthcare & Life Sciences',
    subsector: 'Safety-focused LLM for healthcare',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 278_000_000,
    valuationOrMarketCapUSD: 1_500_000_000,
    employees: 200,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Constitutional AI agents for non-diagnostic clinical tasks; partnership with NVIDIA for voice agents.',
    website: 'https://www.hippocraticai.com',
    dataSource: `${V}: Crunchbase / Forbes, Series B (2024)`,
    asOfDate: '2024-01',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Autonomous Systems & Robotics
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Waymo',
    sector: 'Autonomous Systems & Robotics',
    subsector: 'Robotaxi (Alphabet subsidiary)',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2009,
    revenueUSD: 500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 45_000_000_000,
    employees: 2500,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Alphabet\'s autonomous driving unit; commercial robotaxi service in SF, Phoenix, LA; 20M+ rider-only miles.',
    website: 'https://waymo.com',
    dataSource: `${V}: Alphabet reports / The Information, 2024`,
    asOfDate: '2024-06',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // European AI Leaders
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Aleph Alpha',
    sector: 'Foundation Models',
    subsector: 'Sovereign European LLMs',
    hqCity: 'Heidelberg',
    hqCountry: 'Germany',
    region: 'Europe',
    founded: 2019,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 630_000_000,
    valuationOrMarketCapUSD: 1_500_000_000,
    employees: 300,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Pharia-1-LLM-7B for government/enterprise; explainable AI (AtMan); GDPR-compliant on-prem deployment.',
    website: 'https://aleph-alpha.com',
    dataSource: `${V}: Crunchbase / Handelsblatt, Series B (2023)`,
    asOfDate: '2023-11',
  },
  {
    name: 'DeepL',
    sector: 'Enterprise AI',
    subsector: 'Neural machine translation',
    hqCity: 'Cologne',
    hqCountry: 'Germany',
    region: 'Europe',
    founded: 2017,
    revenueUSD: 200_000_000,
    fundingRaisedUSD: 300_000_000,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 900,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'World\'s most accurate translator (30+ languages); DeepL Write for AI writing; API for enterprise localization.',
    website: 'https://www.deepl.com',
    dataSource: `${V}: Crunchbase / Forbes AI 50, 2023`,
    asOfDate: '2023-05',
  },
  {
    name: 'Pigment',
    sector: 'Enterprise AI',
    subsector: 'AI business planning/finance',
    hqCity: 'Paris',
    hqCountry: 'France',
    region: 'Europe',
    founded: 2019,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 390_000_000,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 500,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'FP&A platform replacing spreadsheets; AI forecasts, scenario modeling, driver-based planning for finance teams.',
    website: 'https://www.pigment.com',
    dataSource: `${V}: Crunchbase / Forbes AI 50, Series D (2024)`,
    asOfDate: '2024-05',
  },
  {
    name: 'Photoroom',
    sector: 'Media & Creativity',
    subsector: 'AI product photography',
    hqCity: 'Paris',
    hqCountry: 'France',
    region: 'Europe',
    founded: 2019,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 130_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 100,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Instant background removal/generation for e-commerce; 150M+ downloads; API for marketplace integration.',
    website: 'https://www.photoroom.com',
    dataSource: `${V}: Crunchbase / Forbes AI 50, Series B (2024)`,
    asOfDate: '2024-02',
  },
  {
    name: 'Siemens',
    sector: 'Enterprise AI',
    subsector: 'Industrial AI + Digital Twin',
    hqCity: 'Munich',
    hqCountry: 'Germany',
    region: 'Europe',
    founded: 1847,
    revenueUSD: 80_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 140_000_000_000,
    employees: 416000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'SIE.DE',
    oneLineDescription:
      'Xcelerator platform: industrial AI for manufacturing, buildings, grids, mobility; NVIDIA Omniverse partnership.',
    website: 'https://www.siemens.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MORE FORTUNE 500 — AI-adjacent tech giants & chip ecosystem
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'SAP',
    sector: 'Enterprise AI',
    subsector: 'ERP + Joule AI copilot',
    hqCity: 'Walldorf',
    hqCountry: 'Germany',
    region: 'Europe',
    founded: 1972,
    revenueUSD: 33_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 210_000_000_000,
    employees: 110000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'SAP',
    oneLineDescription:
      'ERP giant embedding Joule AI copilot across finance, supply chain, and HR modules.',
    website: 'https://www.sap.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Cisco Systems',
    sector: 'AI Infrastructure',
    subsector: 'Networking + AI observability',
    hqCity: 'San Jose',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1984,
    revenueUSD: 57_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 240_000_000_000,
    employees: 84900,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'CSCO',
    oneLineDescription:
      'Network infrastructure leader integrating AI for traffic optimization, security, and observability.',
    website: 'https://www.cisco.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Intuit',
    sector: 'Enterprise AI',
    subsector: 'Financial AI + AI-powered tax/finance',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1983,
    revenueUSD: 14_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 190_000_000_000,
    employees: 18700,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'INTU',
    oneLineDescription:
      'TurboTax and QuickBooks enhanced with AI for automated tax filing, bookkeeping, and financial planning.',
    website: 'https://www.intuit.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Workday',
    sector: 'Enterprise AI',
    subsector: 'HCM + AI-powered HR analytics',
    hqCity: 'Pleasanton',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2005,
    revenueUSD: 8_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 70_000_000_000,
    employees: 18000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'WDAY',
    oneLineDescription:
      'HCM platform adding AI skills inference, workforce planning, and conversational HR assistant.',
    website: 'https://www.workday.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'UiPath',
    sector: 'Enterprise AI',
    subsector: 'RPA + AI document understanding',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2005,
    revenueUSD: 1_200_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 8_000_000_000,
    employees: 5000,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'PATH',
    oneLineDescription:
      'RPA leader combining AI document understanding and generative automation for enterprise workflows.',
    website: 'https://www.uipath.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Autodesk',
    sector: 'Enterprise AI',
    subsector: 'CAD + generative design AI',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1982,
    revenueUSD: 5_500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 55_000_000_000,
    employees: 13500,
    status: 'Public',
    tier: 'public-large',
    ticker: 'ADSK',
    oneLineDescription:
      'AutoCAD, Fusion, and Revit with AI generative design and automated drafting assistants.',
    website: 'https://www.autodesk.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'C3.ai',
    sector: 'Enterprise AI',
    subsector: 'Enterprise AI application platform',
    hqCity: 'Redwood City',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2009,
    revenueUSD: 300_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 4_000_000_000,
    employees: 700,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'AI',
    oneLineDescription:
      'End-to-end AI application platform for predictive maintenance, fraud detection, and supply chain optimization.',
    website: 'https://c3.ai',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'SoundHound AI',
    sector: 'Media & Creativity',
    subsector: 'Conversational AI + voice platform',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2003,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 300,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'SOUN',
    oneLineDescription:
      'Conversational AI platform for restaurants, automotive, and IoT; dynamic conversational actions.',
    website: 'https://soundhound.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'BigCommerce',
    sector: 'Enterprise AI',
    subsector: 'E-commerce + AI merchandising',
    hqCity: 'Austin',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2009,
    revenueUSD: 300_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_500_000_000,
    employees: 1200,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'BIGC',
    oneLineDescription:
      'E-commerce platform integrating AI product recommendations, search, and automated merchandising.',
    website: 'https://www.bigcommerce.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Shopify',
    sector: 'Enterprise AI',
    subsector: 'E-commerce + Shopify Magic AI',
    hqCity: 'Ottawa',
    hqCountry: 'Canada',
    region: 'North America',
    founded: 2006,
    revenueUSD: 7_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 120_000_000_000,
    employees: 12000,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'SHOP',
    oneLineDescription:
      'Commerce platform with Shopify Magic AI for product descriptions, customer support, and merchant analytics.',
    website: 'https://www.shopify.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AI Infrastructure — More cloud/data companies
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Cloudflare',
    sector: 'AI Infrastructure',
    subsector: 'Edge network + Workers AI',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2009,
    revenueUSD: 1_500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 40_000_000_000,
    employees: 3500,
    status: 'Public',
    tier: 'public-large',
    ticker: 'NET',
    oneLineDescription:
      'Edge network running AI inference at 300+ locations; Workers AI platform for serverless ML.',
    website: 'https://www.cloudflare.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Fastly',
    sector: 'AI Infrastructure',
    subsector: 'Edge cloud + real-time compute',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2011,
    revenueUSD: 500_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 1000,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'FSLY',
    oneLineDescription:
      'Edge cloud platform for low-latency compute; adding AI inference at the edge.',
    website: 'https://www.fastly.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Pinecone',
    sector: 'AI Infrastructure',
    subsector: 'Vector database',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2019,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 275_000_000,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 200,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Managed vector database for RAG, semantic search, and AI recommendation systems.',
    website: 'https://www.pinecone.io',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series B (2024)`,
    asOfDate: '2024-01',
  },
  {
    name: 'Weaviate',
    sector: 'AI Infrastructure',
    subsector: 'Open-source vector database',
    hqCity: 'Amsterdam',
    hqCountry: 'Netherlands',
    region: 'Europe',
    founded: 2019,
    revenueUSD: 30_000_000,
    fundingRaisedUSD: 100_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 150,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Open-source vector DB with built-in ML modules for embedding, classification, and generative search.',
    website: 'https://weaviate.io',
    dataSource: `${V}: Crunchbase, Series B (2023)`,
    asOfDate: '2023-06',
  },
  {
    name: 'Qdrant',
    sector: 'AI Infrastructure',
    subsector: 'Vector search engine',
    hqCity: 'Berlin',
    hqCountry: 'Germany',
    region: 'Europe',
    founded: 2021,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 30_000_000,
    valuationOrMarketCapUSD: 300_000_000,
    employees: 60,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'High-performance vector search engine optimized for filtering, quantization, and distributed scaling.',
    website: 'https://qdrant.tech',
    dataSource: `${V}: Crunchbase, seed (2023)`,
    asOfDate: '2023-08',
  },
  {
    name: 'Milvus (Zilliz)',
    sector: 'AI Infrastructure',
    subsector: 'Vector database (open-source)',
    hqCity: 'Shanghai',
    hqCountry: 'China',
    region: 'Asia-Pacific',
    founded: 2019,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 60_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 200,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Open-source vector DB for AI similarity search; Zilliz Cloud is the managed service.',
    website: 'https://milvus.io',
    dataSource: `${V}: Crunchbase, Series B (2022)`,
    asOfDate: '2022-07',
  },
  {
    name: 'Anyscale (Ray)',
    sector: 'AI Infrastructure',
    subsector: 'Distributed compute for AI',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2019,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 300_000_000,
    valuationOrMarketCapUSD: 1_200_000_000,
    employees: 200,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Ray distributed framework for training and serving AI at scale; Anyscale Cloud is the managed platform.',
    website: 'https://www.anyscale.com',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series C (2023)`,
    asOfDate: '2023-10',
  },
  {
    name: 'Modal',
    sector: 'AI Infrastructure',
    subsector: 'Serverless GPU compute',
    hqCity: 'Stockholm',
    hqCountry: 'Sweden',
    region: 'Europe',
    founded: 2021,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 43_000_000,
    valuationOrMarketCapUSD: 300_000_000,
    employees: 30,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Serverless cloud for AI workloads; deploy GPU inference and training in seconds from Python.',
    website: 'https://modal.com',
    dataSource: `${V}: Crunchbase, Series A (2024)`,
    asOfDate: '2024-03',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AI Frontier — More labs and model builders
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'xAI (expanded detail)',
    sector: 'Foundation Models',
    subsector: 'Frontier LLMs (Grok)',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 50_000_000_000,
    valuationOrMarketCapUSD: 80_000_000_000,
    employees: 700,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Elon Musk\'s AI lab building the Grok model family and Colossus supercluster.',
    website: 'https://x.ai',
    dataSource: `${V}: Bloomberg, 2025`,
    asOfDate: '2025-02',
  },
  {
    name: 'Inflection AI',
    sector: 'Foundation Models',
    subsector: 'Personal AI assistant (Pi)',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 1_500_000_000,
    valuationOrMarketCapUSD: 1_200_000_000,
    employees: 200,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Pi personal AI assistant; talent and IP acquired by Microsoft in 2024.',
    website: 'https://inflection.ai',
    dataSource: `${V}: Bloomberg / TechCrunch, acquisition (2024)`,
    asOfDate: '2024-06',
  },
  {
    name: 'Character.AI',
    sector: 'Foundation Models',
    subsector: 'AI companion / character chat',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2021,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 180_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 80,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'AI character chat platform with 50M+ monthly active users; subscription-based monetization.',
    website: 'https://character.ai',
    dataSource: `${V}: Forbes AI 50, 2024`,
    asOfDate: '2024-06',
  },
  {
    name: 'Reka AI',
    sector: 'Foundation Models',
    subsector: 'Multimodal frontier models',
    hqCity: 'London',
    hqCountry: 'United Kingdom',
    region: 'Europe',
    founded: 2023,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 210_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 80,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Multimodal AI startup founded by DeepMind alumni; Reka Flash and Core models for enterprise.',
    website: 'https://reka.ai',
    dataSource: `${V}: Crunchbase / Reuters, Series A (2024)`,
    asOfDate: '2024-03',
  },
  {
    name: 'Moonshot AI (Kimi)',
    sector: 'Foundation Models',
    subsector: 'Chinese LLM (Kimi assistant)',
    hqCity: 'Beijing',
    hqCountry: 'China',
    region: 'Asia-Pacific',
    founded: 2023,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 800_000_000,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 300,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Kimi chat app with 2M+ context window; one of China\'s fastest-growing AI startups.',
    website: 'https://kimi.ai',
    dataSource: `${V}: Reuters / Bloomberg, 2025`,
    asOfDate: '2025-04',
  },
  {
    name: 'MiniMax',
    sector: 'Foundation Models',
    subsector: 'Chinese multimodal LLM',
    hqCity: 'Shanghai',
    hqCountry: 'China',
    region: 'Asia-Pacific',
    founded: 2021,
    revenueUSD: 30_000_000,
    fundingRaisedUSD: 800_000_000,
    valuationOrMarketCapUSD: 2_500_000_000,
    employees: 200,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Chinese AI startup building multimodal foundation models for text, voice, and video generation.',
    website: 'https://minimax.chat',
    dataSource: `${V}: 36Kr / Bloomberg, Series B (2024)`,
    asOfDate: '2024-10',
  },
  {
    name: 'Zhipu AI',
    sector: 'Foundation Models',
    subsector: 'Chinese LLM (ChatGLM)',
    hqCity: 'Beijing',
    hqCountry: 'China',
    region: 'Asia-Pacific',
    founded: 2019,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 600_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 500,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Leading Chinese AI lab; ChatGLM open-source model series and CogView image generation.',
    website: 'https://zhipuai.cn',
    dataSource: `${V}: Bloomberg / 36Kr, Series D (2024)`,
    asOfDate: '2024-08',
  },
  {
    name: '01.AI (Yi)',
    sector: 'Foundation Models',
    subsector: 'Chinese LLM (Yi model family)',
    hqCity: 'Beijing',
    hqCountry: 'China',
    region: 'Asia-Pacific',
    founded: 2023,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 300_000_000,
    valuationOrMarketCapUSD: 3_000_000_000,
    employees: 200,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Kai-Fu Lee\'s AI lab; Yi open-source model series and Yi-Large commercial API.',
    website: 'https://www.01.ai',
    dataSource: `${V}: Bloomberg, 2024`,
    asOfDate: '2024-05',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // AI Agent Platforms
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'LangChain',
    sector: 'Developer Tools',
    subsector: 'LLM app framework',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 40_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 50,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Dominant framework for building LLM applications; LangSmith for observability and LangGraph for agents.',
    website: 'https://www.langchain.com',
    dataSource: `${V}: Crunchbase, Series A (2023)`,
    asOfDate: '2023-06',
  },
  {
    name: 'LlamaIndex',
    sector: 'Developer Tools',
    subsector: 'RAG framework',
    hqCity: 'Seattle',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 20_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 30,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Leading RAG (retrieval-augmented generation) framework for connecting LLMs to private data.',
    website: 'https://www.llamaindex.ai',
    dataSource: `${V}: Crunchbase, seed (2024)`,
    asOfDate: '2024-04',
  },
  {
    name: 'CrewAI',
    sector: 'Developer Tools',
    subsector: 'Multi-agent orchestration',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: 5_000_000,
    fundingRaisedUSD: 18_000_000,
    valuationOrMarketCapUSD: 200_000_000,
    employees: 15,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Open-source multi-agent orchestration framework for building collaborative AI agent teams.',
    website: 'https://www.crewai.com',
    dataSource: `${V}: Crunchbase, seed (2024)`,
    asOfDate: '2024-07',
  },
  {
    name: 'n8n',
    sector: 'Developer Tools',
    subsector: 'Workflow automation + AI nodes',
    hqCity: 'Berlin',
    hqCountry: 'Germany',
    region: 'Europe',
    founded: 2019,
    revenueUSD: 30_000_000,
    fundingRaisedUSD: 48_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 200,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Open-source workflow automation with 400+ integrations; AI nodes for LLM-based workflow steps.',
    website: 'https://n8n.io',
    dataSource: `${V}: Crunchbase, Series A (2024)`,
    asOfDate: '2024-03',
  },
  {
    name: 'AutoGen (Microsoft)',
    sector: 'Developer Tools',
    subsector: 'Multi-agent conversation framework',
    hqCity: 'Redmond',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: null,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: null,
    employees: 100,
    status: 'Public',
    tier: 'fortune500',
    ticker: 'MSFT',
    oneLineDescription:
      'Open-source multi-agent framework from Microsoft Research; enables LLM agents to converse and collaborate.',
    website: 'https://microsoft.github.io/autogen',
    dataSource: `${V}: GitHub / Microsoft Research`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Cybersecurity — More AI security companies
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'SentinelOne',
    sector: 'Cybersecurity',
    subsector: 'AI-native endpoint + Singularity',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2013,
    revenueUSD: 700_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 7_000_000_000,
    employees: 2500,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'S',
    oneLineDescription:
      'Purple AI copilot for security operations; autonomous endpoint protection and cloud workload security.',
    website: 'https://www.sentinelone.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Tenable',
    sector: 'Cybersecurity',
    subsector: 'Vulnerability management + AI',
    hqCity: 'Columbia',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2002,
    revenueUSD: 800_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 4_000_000_000,
    employees: 2200,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'TENB',
    oneLineDescription:
      'Cyber exposure platform using AI for predictive vulnerability prioritization and risk scoring.',
    website: 'https://www.tenable.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Generative Media — More companies
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Kling (Kuaishou)',
    sector: 'Media & Creativity',
    subsector: 'AI video generation',
    hqCity: 'Beijing',
    hqCountry: 'China',
    region: 'Asia-Pacific',
    founded: 2024,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 500,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'AI video generation model rivaling Sora; 1080p video up to 2 minutes from text prompts.',
    website: 'https://klingai.com',
    dataSource: `industry estimates, 2025`,
    asOfDate: '2025-01',
  },
  {
    name: 'Pika Labs',
    sector: 'Media & Creativity',
    subsector: 'AI video generation',
    hqCity: 'Palo Alto',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2023,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 110_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 40,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Text-to-video and image-to-video platform; Pika 1.5 adds effects like melting, exploding, inflating.',
    website: 'https://pika.art',
    dataSource: `${V}: Crunchbase / TechCrunch, Series B (2024)`,
    asOfDate: '2024-07',
  },
  {
    name: 'Luma AI',
    sector: 'Media & Creativity',
    subsector: '3D capture + video generation (Dream Machine)',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2021,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 65_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 50,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Dream Machine video generation model; NeRF-based 3D capture for spatial computing.',
    website: 'https://lumalabs.ai',
    dataSource: `${V}: Crunchbase / Forbes AI 50, 2024`,
    asOfDate: '2024-06',
  },
  {
    name: 'HeyGen',
    sector: 'Media & Creativity',
    subsector: 'AI avatar video platform',
    hqCity: 'Los Angeles',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2020,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: 60_000_000,
    valuationOrMarketCapUSD: 1_000_000_000,
    employees: 200,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'AI avatar video creation with 100+ languages; viral deepfake-style video tool with enterprise use.',
    website: 'https://www.heygen.com',
    dataSource: `${V}: Crunchbase / Forbes AI 50, 2024`,
    asOfDate: '2024-09',
  },
  {
    name: 'Jasper AI',
    sector: 'Media & Creativity',
    subsector: 'AI marketing copywriting',
    hqCity: 'Austin',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2021,
    revenueUSD: 75_000_000,
    fundingRaisedUSD: 125_000_000,
    valuationOrMarketCapUSD: 1_500_000_000,
    employees: 200,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'AI content generation platform for marketing, blog posts, ad copy, and brand voice management.',
    website: 'https://www.jasper.ai',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, 2023`,
    asOfDate: '2023-06',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Healthcare & Biotech — More AI
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Tempus AI',
    sector: 'Healthcare & Life Sciences',
    subsector: 'Precision medicine + AI',
    hqCity: 'Chicago',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2015,
    revenueUSD: 1_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 8_000_000_000,
    employees: 3000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'TEM',
    oneLineDescription:
      'Largest library of clinical and molecular data; AI for precision oncology and clinical decision support.',
    website: 'https://www.tempus.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Schrödinger',
    sector: 'Healthcare & Life Sciences',
    subsector: 'Computational drug discovery',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1991,
    revenueUSD: 300_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 800,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'SDGR',
    oneLineDescription:
      'Physics-based and ML drug discovery platform; own pipeline of small-molecule therapeutics.',
    website: 'https://www.schrodinger.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Absci',
    sector: 'Healthcare & Life Sciences',
    subsector: 'Generative AI biologics design',
    hqCity: 'Vancouver',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2012,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 800_000_000,
    employees: 300,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'ABSI',
    oneLineDescription:
      'Generative AI platform for designing de novo biologics and antibodies from scratch.',
    website: 'https://absci.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Isomorphic Labs (DeepMind)',
    sector: 'Healthcare & Life Sciences',
    subsector: 'AI drug discovery (Alphabet)',
    hqCity: 'London',
    hqCountry: 'United Kingdom',
    region: 'Europe',
    founded: 2021,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 500,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Alphabet spinout from DeepMind applying AlphaFold and AI to drug discovery and target identification.',
    website: 'https://www.isomorphiclabs.com',
    dataSource: `${V}: Alphabet / Nature, 2024`,
    asOfDate: '2024-06',
  },
  {
    name: 'Nabla Bio',
    sector: 'Healthcare & Life Sciences',
    subsector: 'Generative AI antibodies',
    hqCity: 'Boston',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2021,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 130_000_000,
    valuationOrMarketCapUSD: 500_000_000,
    employees: 100,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Generative AI antibody design; first AI-designed antibody entered IND-enabling studies.',
    website: 'https://nabla.bio',
    dataSource: `${V}: Crunchbase / Forbes AI 50, Series B (2023)`,
    asOfDate: '2023-06',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Autonomous Systems & Robotics — More
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Figure AI',
    sector: 'Autonomous Systems & Robotics',
    subsector: 'General-purpose humanoid robots',
    hqCity: 'Sunnyvale',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 10_000_000,
    fundingRaisedUSD: 900_000_000,
    valuationOrMarketCapUSD: 2_600_000_000,
    employees: 300,
    status: 'Private',
    tier: 'ai-frontier',
    ticker: null,
    oneLineDescription:
      'Figure 01 humanoid robot with OpenAI partnership; capable of natural language reasoning and manipulation.',
    website: 'https://www.figure.ai',
    dataSource: `${V}: Bloomberg / Forbes AI 50, Series B (2024)`,
    asOfDate: '2024-09',
  },
  {
    name: 'Zoox (Amazon)',
    sector: 'Autonomous Systems & Robotics',
    subsector: 'Robotaxi (Amazon subsidiary)',
    hqCity: 'Foster City',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2014,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 15_000_000_000,
    employees: 2000,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Amazon\'s autonomous vehicle subsidiary; purpose-built robotaxi with no steering wheel, operating in Las Vegas.',
    website: 'https://zoox.com',
    dataSource: `${V}: Amazon reports, 2024`,
    asOfDate: '2024-06',
  },
  {
    name: 'Aurora Innovation',
    sector: 'Autonomous Systems & Robotics',
    subsector: 'Self-driving trucking',
    hqCity: 'Pittsburgh',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2017,
    revenueUSD: 50_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 1500,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'AUR',
    oneLineDescription:
      'Aurora Driver for autonomous trucking; commercial launch planned on Texas I-45 corridor.',
    website: 'https://aurora.tech',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Legal & FinTech AI
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Harvey AI',
    sector: 'Enterprise AI',
    subsector: 'AI legal assistant',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2022,
    revenueUSD: 20_000_000,
    fundingRaisedUSD: 240_000_000,
    valuationOrMarketCapUSD: 3_500_000_000,
    employees: 200,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'AI legal assistant trained on case law and statutes; adopted by top global law firms.',
    website: 'https://www.harvey.ai',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series B (2024)`,
    asOfDate: '2024-03',
  },
  {
    name: 'Ironclad',
    sector: 'Enterprise AI',
    subsector: 'AI contract lifecycle management',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2014,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: 370_000_000,
    valuationOrMarketCapUSD: 2_000_000_000,
    employees: 600,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'AI-powered contract management platform; automated review, redlining, and risk scoring.',
    website: 'https://www.ironcladapp.com',
    dataSource: `${V}: Crunchbase, Series E (2023)`,
    asOfDate: '2023-11',
  },
  {
    name: 'Ramp',
    sector: 'Enterprise AI',
    subsector: 'AI spend management',
    hqCity: 'New York',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2019,
    revenueUSD: 500_000_000,
    fundingRaisedUSD: 1_400_000_000,
    valuationOrMarketCapUSD: 13_000_000_000,
    employees: 1000,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'Corporate cards and AI-powered expense management; automated receipt matching and anomaly detection.',
    website: 'https://ramp.com',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series D (2024)`,
    asOfDate: '2024-05',
  },
  {
    name: 'Brex',
    sector: 'Enterprise AI',
    subsector: 'AI-powered fintech for startups',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2016,
    revenueUSD: 500_000_000,
    fundingRaisedUSD: 1_500_000_000,
    valuationOrMarketCapUSD: 12_000_000_000,
    employees: 1500,
    status: 'Private',
    tier: 'unicorn',
    ticker: null,
    oneLineDescription:
      'AI-powered financial platform for startups; corporate cards, bill pay, and automated expense tracking.',
    website: 'https://www.brex.com',
    dataSource: `${V}: Forbes AI 50 / Crunchbase, Series D (2024)`,
    asOfDate: '2024-03',
  },
  {
    name: 'Stripe',
    sector: 'Enterprise AI',
    subsector: 'Payments + AI fraud detection',
    hqCity: 'San Francisco',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2010,
    revenueUSD: 18_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 120_000_000_000,
    employees: 8000,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Payment infrastructure with AI-powered fraud detection (Stripe Radar) and Revenue Recognition.',
    website: 'https://stripe.com',
    dataSource: `${V}: Forbes AI 50, 2024`,
    asOfDate: '2024-03',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // Education AI
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Duolingo',
    sector: 'Enterprise AI',
    subsector: 'AI language learning',
    hqCity: 'Pittsburgh',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2011,
    revenueUSD: 600_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 16_000_000_000,
    employees: 800,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'DUOL',
    oneLineDescription:
      'AI-powered language learning platform with GPT-4 roleplay conversations and personalized curriculum.',
    website: 'https://www.duolingo.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Coursera',
    sector: 'Enterprise AI',
    subsector: 'AI-powered online education',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2012,
    revenueUSD: 700_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 5_000_000_000,
    employees: 1500,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'COUR',
    oneLineDescription:
      'AI learning coach (Coach) and GenAI course creation from leading universities and companies.',
    website: 'https://www.coursera.org',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Khan Academy (Khanmigo)',
    sector: 'Enterprise AI',
    subsector: 'AI tutoring',
    hqCity: 'Mountain View',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2008,
    revenueUSD: 100_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: null,
    employees: 300,
    status: 'Private',
    tier: 'big-tech',
    ticker: null,
    oneLineDescription:
      'Khanmigo AI tutor built on GPT-4; guides students with Socratic dialogue instead of giving answers.',
    website: 'https://www.khanacademy.org',
    dataSource: `${V}: Khan Academy blog, 2024`,
    asOfDate: '2024-06',
  },

  // ─────────────────────────────────────────────────────────────────────────
  // More Semiconductor / AI Hardware
  // ─────────────────────────────────────────────────────────────────────────
  {
    name: 'Marvell Technology',
    sector: 'AI Hardware',
    subsector: 'Custom AI silicon + networking',
    hqCity: 'Wilmington',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1995,
    revenueUSD: 6_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 70_000_000_000,
    employees: 6000,
    status: 'Public',
    tier: 'public-large',
    ticker: 'MRVL',
    oneLineDescription:
      'Custom AI accelerators (ASICs) for hyperscalers; custom compute and networking silicon.',
    website: 'https://www.marvell.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Monolithic Power Systems',
    sector: 'AI Hardware',
    subsector: 'Power management for AI datacenters',
    hqCity: 'Kirkland',
    hqCountry: 'United States',
    region: 'North America',
    founded: 1997,
    revenueUSD: 2_000_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 50_000_000_000,
    employees: 3500,
    status: 'Public',
    tier: 'public-large',
    ticker: 'MPWR',
    oneLineDescription:
      'Power management ICs critical for AI GPU power delivery; beneficiary of AI datacenter buildout.',
    website: 'https://www.monolithicpower.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
  {
    name: 'Astera Labs',
    sector: 'AI Hardware',
    subsector: 'AI connectivity (CXL/PCIe retimers)',
    hqCity: 'Santa Clara',
    hqCountry: 'United States',
    region: 'North America',
    founded: 2017,
    revenueUSD: 400_000_000,
    fundingRaisedUSD: null,
    valuationOrMarketCapUSD: 18_000_000_000,
    employees: 500,
    status: 'Public',
    tier: 'public-mid',
    ticker: 'ALAB',
    oneLineDescription:
      'AI connectivity semiconductors; CXL and PCIe retimers enabling GPU-to-GPU communication in datacenters.',
    website: 'https://www.asteralabs.com',
    dataSource: `${V}: Yahoo Finance, market cap`,
    asOfDate: SNAP,
  },
];

// ─────────────────────────────────────────────────────────────────────────
// Build pipeline — invoked via `npm run build:data` (npx tsx scripts/build-data.ts)
// ─────────────────────────────────────────────────────────────────────────
const outDir = join(process.cwd(), 'data');
mkdirSync(outDir, { recursive: true });

const ranked = [...COMPANIES].sort(
  (a, b) =>
    (b.valuationOrMarketCapUSD ?? 0) - (a.valuationOrMarketCapUSD ?? 0) ||
    (b.fundingRaisedUSD ?? 0) - (a.fundingRaisedUSD ?? 0) ||
    a.name.localeCompare(b.name),
).map((c, i) => ({ ...c, rank: i + 1 }));

writeFileSync(
  join(outDir, 'companies.json'),
  JSON.stringify(ranked, null, 2),
  'utf8',
);

const header = 'rank,name,sector,tier,status,revenueUSD,valuationOrMarketCapUSD,fundingRaisedUSD,employees,hqCountry,hqCity,founded,website,dataSource,asOfDate';
const rows = ranked.map((c) =>
  [
    c.rank,
    `"${c.name}"`,
    `"${c.sector}"`,
    c.tier,
    c.status,
    c.revenueUSD ?? '',
    c.valuationOrMarketCapUSD ?? '',
    c.fundingRaisedUSD ?? '',
    c.employees ?? '',
    `"${c.hqCountry}"`,
    `"${c.hqCity}"`,
    c.founded ?? '',
    c.website ?? '',
    `"${c.dataSource}"`,
    c.asOfDate ?? '',
  ].join(','),
);
writeFileSync(join(outDir, 'companies.csv'), [header, ...rows].join('\n'), 'utf8');

console.log(`✅ Built ${ranked.length} companies → data/companies.json & data/companies.csv`);
